// AUTO-GENERATED — DE gear ItemType (uniqueName) → display name, for the
// masterable equipment AOWA tracks (WFCD `masterable:true`). Name matches
// AOWA's Equipment craftable name (both are the WFCD `name`), so the backend
// marks owned/mastered by name. Regenerate with scripts/gen-gear.mjs.
// 803 entries.
export const GEAR_NAMES: Record<string, string> = {
  "/Lotus/Powersuits/Alchemist/Alchemist": "Lavos",
  "/Lotus/Powersuits/Alchemist/LavosPrime": "Lavos Prime",
  "/Lotus/Powersuits/AntiMatter/Anti": "Nova",
  "/Lotus/Powersuits/AntiMatter/NovaPrime": "Nova Prime",
  "/Lotus/Powersuits/Archwing/DemolitionJetPack/DemolitionJetPack": "Elytron",
  "/Lotus/Powersuits/Archwing/PrimeJetPack/PrimeJetPack": "Odonata Prime",
  "/Lotus/Powersuits/Archwing/StandardJetPack/StandardJetPack": "Odonata",
  "/Lotus/Powersuits/Archwing/StealthJetPack/StealthJetPack": "Itzal",
  "/Lotus/Powersuits/Archwing/SupportJetPack/SupportJetPack": "Amesha",
  "/Lotus/Powersuits/Banshee/Banshee": "Banshee",
  "/Lotus/Powersuits/Banshee/BansheePrime": "Banshee Prime",
  "/Lotus/Powersuits/Bard/Bard": "Octavia",
  "/Lotus/Powersuits/Bard/OctaviaPrime": "Octavia Prime",
  "/Lotus/Powersuits/Berserker/Berserker": "Valkyr",
  "/Lotus/Powersuits/Berserker/ValkyrPrime": "Valkyr Prime",
  "/Lotus/Powersuits/Brawler/AtlasPrime": "Atlas Prime",
  "/Lotus/Powersuits/Brawler/Brawler": "Atlas",
  "/Lotus/Powersuits/BrokenFrame/BrokenFrame": "Xaku",
  "/Lotus/Powersuits/BrokenFrame/XakuPrime": "Xaku Prime",
  "/Lotus/Powersuits/Choir/Choir": "Jade",
  "/Lotus/Powersuits/ConcreteFrame/ConcreteFrame": "Qorvex",
  "/Lotus/Powersuits/Cowgirl/Cowgirl": "Mesa",
  "/Lotus/Powersuits/Cowgirl/MesaPrime": "Mesa Prime",
  "/Lotus/Powersuits/Dagath/Dagath": "Dagath",
  "/Lotus/Powersuits/DemonFrame/DemonFrame": "Uriel",
  "/Lotus/Powersuits/Devourer/Devourer": "Grendel",
  "/Lotus/Powersuits/Devourer/GrendelPrime": "Grendel Prime",
  "/Lotus/Powersuits/Dragon/ChromaPrime": "Chroma Prime",
  "/Lotus/Powersuits/Dragon/Dragon": "Chroma",
  "/Lotus/Powersuits/Ember/Ember": "Ember",
  "/Lotus/Powersuits/Ember/EmberPrime": "Ember Prime",
  "/Lotus/Powersuits/EntratiMech/NechroTech": "Voidrig",
  "/Lotus/Powersuits/EntratiMech/ThanoTech": "Bonewidow",
  "/Lotus/Powersuits/Excalibur/Excalibur": "Excalibur",
  "/Lotus/Powersuits/Excalibur/ExcaliburPrime": "Excalibur Prime",
  "/Lotus/Powersuits/Excalibur/ExcaliburUmbra": "Excalibur Umbra",
  "/Lotus/Powersuits/Fairy/Fairy": "Titania",
  "/Lotus/Powersuits/Fairy/TitaniaPrime": "Titania Prime",
  "/Lotus/Powersuits/Frost/Frost": "Frost",
  "/Lotus/Powersuits/Frost/FrostPrime": "Frost Prime",
  "/Lotus/Powersuits/Frumentarius/Frumentarius": "Cyte-09",
  "/Lotus/Powersuits/Garuda/Garuda": "Garuda",
  "/Lotus/Powersuits/Garuda/GarudaPrime": "Garuda Prime",
  "/Lotus/Powersuits/Geode/Geode": "Citrine",
  "/Lotus/Powersuits/Glass/GaraPrime": "Gara Prime",
  "/Lotus/Powersuits/Glass/Glass": "Gara",
  "/Lotus/Powersuits/Gyre/Gyre": "Gyre",
  "/Lotus/Powersuits/Gyre/GyrePrime": "Gyre Prime",
  "/Lotus/Powersuits/Harlequin/Harlequin": "Mirage",
  "/Lotus/Powersuits/Harlequin/MiragePrime": "Mirage Prime",
  "/Lotus/Powersuits/Hoplite/Hoplite": "Styanax",
  "/Lotus/Powersuits/Hoplite/StyanaxPrime": "Styanax Prime",
  "/Lotus/Powersuits/Infestation/Infestation": "Nidus",
  "/Lotus/Powersuits/Infestation/InfestationPrime": "Nidus Prime",
  "/Lotus/Powersuits/Inkblot/Inkblot": "Follie",
  "/Lotus/Powersuits/IronFrame/IronFrame": "Hildryn",
  "/Lotus/Powersuits/IronFrame/IronFramePrime": "Hildryn Prime",
  "/Lotus/Powersuits/Jade/Jade": "Nyx",
  "/Lotus/Powersuits/Jade/NyxPrime": "Nyx Prime",
  "/Lotus/Powersuits/Khora/Khora": "Khora",
  "/Lotus/Powersuits/Khora/KhoraPrime": "Khora Prime",
  "/Lotus/Powersuits/Koumei/Koumei": "Koumei",
  "/Lotus/Powersuits/Loki/Loki": "Loki",
  "/Lotus/Powersuits/Loki/LokiPrime": "Loki Prime",
  "/Lotus/Powersuits/Mag/Mag": "Mag",
  "/Lotus/Powersuits/Mag/MagPrime": "Mag Prime",
  "/Lotus/Powersuits/Magician/LimboPrime": "Limbo Prime",
  "/Lotus/Powersuits/Magician/Magician": "Limbo",
  "/Lotus/Powersuits/MonkeyKing/MonkeyKing": "Wukong",
  "/Lotus/Powersuits/MonkeyKing/WukongPrime": "Wukong Prime",
  "/Lotus/Powersuits/Necro/Necro": "Nekros",
  "/Lotus/Powersuits/Necro/NekrosPrime": "Nekros Prime",
  "/Lotus/Powersuits/Nezha/Nezha": "Nezha",
  "/Lotus/Powersuits/Nezha/NezhaPrime": "Nezha Prime",
  "/Lotus/Powersuits/Ninja/AshPrime": "Ash Prime",
  "/Lotus/Powersuits/Ninja/Ninja": "Ash",
  "/Lotus/Powersuits/Nokko/Nokko": "Nokko",
  "/Lotus/Powersuits/Odalisk/Odalisk": "Protea",
  "/Lotus/Powersuits/Odalisk/ProteaPrime": "Protea Prime",
  "/Lotus/Powersuits/Oraxia/Oraxia": "Oraxia",
  "/Lotus/Powersuits/Pacifist/BaruukPrime": "Baruuk Prime",
  "/Lotus/Powersuits/Pacifist/Pacifist": "Baruuk",
  "/Lotus/Powersuits/Pagemaster/Pagemaster": "Dante",
  "/Lotus/Powersuits/Paladin/Paladin": "Oberon",
  "/Lotus/Powersuits/Paladin/PaladinPrime": "Oberon Prime",
  "/Lotus/Powersuits/PaxDuviricus/PaxDuviricus": "Kullervo",
  "/Lotus/Powersuits/Pirate/HydroidPrime": "Hydroid Prime",
  "/Lotus/Powersuits/Pirate/Pirate": "Hydroid",
  "/Lotus/Powersuits/Priest/HarrowPrime": "Harrow Prime",
  "/Lotus/Powersuits/Priest/Priest": "Harrow",
  "/Lotus/Powersuits/Ranger/IvaraPrime": "Ivara Prime",
  "/Lotus/Powersuits/Ranger/Ranger": "Ivara",
  "/Lotus/Powersuits/Revenant/Revenant": "Revenant",
  "/Lotus/Powersuits/Revenant/RevenantPrime": "Revenant Prime",
  "/Lotus/Powersuits/Rhino/Rhino": "Rhino",
  "/Lotus/Powersuits/Rhino/RhinoPrime": "Rhino Prime",
  "/Lotus/Powersuits/Runner/GaussPrime": "Gauss Prime",
  "/Lotus/Powersuits/Runner/Runner": "Gauss",
  "/Lotus/Powersuits/Sandman/InarosPrime": "Inaros Prime",
  "/Lotus/Powersuits/Sandman/Sandman": "Inaros",
  "/Lotus/Powersuits/Saryn/Saryn": "Saryn",
  "/Lotus/Powersuits/Saryn/SarynPrime": "Saryn Prime",
  "/Lotus/Powersuits/Sentient/CalibanPrime": "Caliban Prime",
  "/Lotus/Powersuits/Sentient/Sentient": "Caliban",
  "/Lotus/Powersuits/SiriusOrion/OrionSuit": "Orion & Sirius",
  "/Lotus/Powersuits/SiriusOrion/SiriusSuit": "Sirius & Orion",
  "/Lotus/Powersuits/Temple/Temple": "Temple",
  "/Lotus/Powersuits/Tengu/Tengu": "Zephyr",
  "/Lotus/Powersuits/Tengu/ZephyrPrime": "Zephyr Prime",
  "/Lotus/Powersuits/Trapper/Trapper": "Vauban",
  "/Lotus/Powersuits/Trapper/TrapperPrime": "Vauban Prime",
  "/Lotus/Powersuits/Trinity/Trinity": "Trinity",
  "/Lotus/Powersuits/Trinity/TrinityPrime": "Trinity Prime",
  "/Lotus/Powersuits/Volt/Volt": "Volt",
  "/Lotus/Powersuits/Volt/VoltPrime": "Volt Prime",
  "/Lotus/Powersuits/Werewolf/VorunaPrime": "Voruna Prime",
  "/Lotus/Powersuits/Werewolf/Werewolf": "Voruna",
  "/Lotus/Powersuits/Wisp/Wisp": "Wisp",
  "/Lotus/Powersuits/Wisp/WispPrime": "Wisp Prime",
  "/Lotus/Powersuits/Wraith/SevagothPrime": "Sevagoth Prime",
  "/Lotus/Powersuits/Wraith/Wraith": "Sevagoth",
  "/Lotus/Powersuits/Yareli/Yareli": "Yareli",
  "/Lotus/Powersuits/Yareli/YareliPrime": "Yareli Prime",
  "/Lotus/Powersuits/YinYang/EquinoxPrime": "Equinox Prime",
  "/Lotus/Powersuits/YinYang/YinYang": "Equinox",
  "/Lotus/Types/Friendly/Pets/CreaturePets/ArmoredInfestedCatbrowPetPowerSuit": "Panzer Vulpaphyla",
  "/Lotus/Types/Friendly/Pets/CreaturePets/HornedInfestedCatbrowPetPowerSuit": "Crescent Vulpaphyla",
  "/Lotus/Types/Friendly/Pets/CreaturePets/MedjayPredatorKubrowPetPowerSuit": "Medjay Predasite",
  "/Lotus/Types/Friendly/Pets/CreaturePets/PharaohPredatorKubrowPetPowerSuit": "Pharaoh Predasite",
  "/Lotus/Types/Friendly/Pets/CreaturePets/VizierPredatorKubrowPetPowerSuit": "Vizier Predasite",
  "/Lotus/Types/Friendly/Pets/CreaturePets/VulpineInfestedCatbrowPetPowerSuit": "Sly Vulpaphyla",
  "/Lotus/Types/Friendly/Pets/MoaPets/MoaPetComponents/CryoxionWeapon": "Cryotra",
  "/Lotus/Types/Friendly/Pets/MoaPets/MoaPetComponents/HextraWeapon": "Multron",
  "/Lotus/Types/Friendly/Pets/MoaPets/MoaPetComponents/SwarmerWeapon": "Helstrum",
  "/Lotus/Types/Friendly/Pets/MoaPets/MoaPetComponents/TazronWeapon": "Tazicor",
  "/Lotus/Types/Friendly/Pets/MoaPets/MoaPetComponents/ThermocorMoaWeapon": "Vulcax",
  "/Lotus/Types/Friendly/Pets/MoaPets/MoaPetParts/MoaPetHeadLambeo": "Lambeo Moa",
  "/Lotus/Types/Friendly/Pets/MoaPets/MoaPetParts/MoaPetHeadMelee": "Nychus Moa",
  "/Lotus/Types/Friendly/Pets/MoaPets/MoaPetParts/MoaPetHeadOloro": "Oloro Moa",
  "/Lotus/Types/Friendly/Pets/MoaPets/MoaPetParts/MoaPetHeadPara": "Para Moa",
  "/Lotus/Types/Friendly/Pets/ZanukaPets/ZanukaPetMeleeWeaponIP": "Batoten",
  "/Lotus/Types/Friendly/Pets/ZanukaPets/ZanukaPetMeleeWeaponIS": "Lacerten",
  "/Lotus/Types/Friendly/Pets/ZanukaPets/ZanukaPetMeleeWeaponPS": "Akaten",
  "/Lotus/Types/Friendly/Pets/ZanukaPets/ZanukaPetParts/ZanukaPetPartHeadA": "Dorma Hound",
  "/Lotus/Types/Friendly/Pets/ZanukaPets/ZanukaPetParts/ZanukaPetPartHeadB": "Bhaira Hound",
  "/Lotus/Types/Friendly/Pets/ZanukaPets/ZanukaPetParts/ZanukaPetPartHeadC": "Hec Hound",
  "/Lotus/Types/Friendly/PlayerControllable/Weapons/DuviriDualSwordsWeapon": "Sun & Moon",
  "/Lotus/Types/Game/CatbrowPet/CheshireCatbrowPetPowerSuit": "Smeeta Kavat",
  "/Lotus/Types/Game/CatbrowPet/MirrorCatbrowPetPowerSuit": "Adarza Kavat",
  "/Lotus/Types/Game/CatbrowPet/VampireCatbrowPetPowerSuit": "Vasca Kavat",
  "/Lotus/Types/Game/KubrowPet/AdventurerKubrowPetPowerSuit": "Sahasa Kubrow",
  "/Lotus/Types/Game/KubrowPet/ChargerKubrowPetPowerSuit": "Helminth Charger",
  "/Lotus/Types/Game/KubrowPet/FurtiveKubrowPetPowerSuit": "Huras Kubrow",
  "/Lotus/Types/Game/KubrowPet/GuardKubrowPetPowerSuit": "Raksa Kubrow",
  "/Lotus/Types/Game/KubrowPet/HunterKubrowPetPowerSuit": "Sunika Kubrow",
  "/Lotus/Types/Game/KubrowPet/RetrieverKubrowPetPowerSuit": "Chesa Kubrow",
  "/Lotus/Types/Sentinels/SentinelPowersuits/ArcDronePowerSuit": "Diriga",
  "/Lotus/Types/Sentinels/SentinelPowersuits/CarrierPowerSuit": "Carrier",
  "/Lotus/Types/Sentinels/SentinelPowersuits/DethCubePowerSuit": "Dethcube",
  "/Lotus/Types/Sentinels/SentinelPowersuits/EmpyreanSentinelPowerSuit": "Nautilus",
  "/Lotus/Types/Sentinels/SentinelPowersuits/GubberPowerSuit": "Djinn",
  "/Lotus/Types/Sentinels/SentinelPowersuits/MeleePetPowerSuit": "Helios",
  "/Lotus/Types/Sentinels/SentinelPowersuits/NautilusPrimeSentinelPowerSuit": "Nautilus Prime",
  "/Lotus/Types/Sentinels/SentinelPowersuits/PrimeCarrierPowerSuit": "Carrier Prime",
  "/Lotus/Types/Sentinels/SentinelPowersuits/PrimeDethCubePowerSuit": "Dethcube Prime",
  "/Lotus/Types/Sentinels/SentinelPowersuits/PrimeHeliosPowerSuit": "Helios Prime",
  "/Lotus/Types/Sentinels/SentinelPowersuits/PrimeShadePowerSuit": "Shade Prime",
  "/Lotus/Types/Sentinels/SentinelPowersuits/PrimeWyrmPowerSuit": "Wyrm Prime",
  "/Lotus/Types/Sentinels/SentinelPowersuits/PrismaShadePowerSuit": "Prisma Shade",
  "/Lotus/Types/Sentinels/SentinelPowersuits/RadarPowerSuit": "Oxylus",
  "/Lotus/Types/Sentinels/SentinelPowersuits/ShadePowerSuit": "Shade",
  "/Lotus/Types/Sentinels/SentinelPowersuits/TnSentinelCrossPowerSuit": "Taxon",
  "/Lotus/Types/Sentinels/SentinelPowersuits/WyrmPowerSuit": "Wyrm",
  "/Lotus/Types/Sentinels/SentinelWeapons/BurstLaserPistol": "Burst Laser",
  "/Lotus/Types/Sentinels/SentinelWeapons/DeconstructorPrime/PrimeHeliosGlaiveWeapon": "Deconstructor Prime",
  "/Lotus/Types/Sentinels/SentinelWeapons/DethMachineRifle": "Deth Machine Rifle",
  "/Lotus/Types/Sentinels/SentinelWeapons/Gremlin": "Artax",
  "/Lotus/Types/Sentinels/SentinelWeapons/LaserRifle": "Laser Rifle",
  "/Lotus/Types/Sentinels/SentinelWeapons/PrimeBurstLaserPistol": "Burst Laser Prime",
  "/Lotus/Types/Sentinels/SentinelWeapons/PrimeDethMachineRifle": "Deth Machine Rifle Prime",
  "/Lotus/Types/Sentinels/SentinelWeapons/PrimeLaserRifle": "Prime Laser Rifle",
  "/Lotus/Types/Sentinels/SentinelWeapons/PrimeSentShotgun": "Sweeper Prime",
  "/Lotus/Types/Sentinels/SentinelWeapons/PrismaBurstLaserPistol": "Prisma Burst Laser",
  "/Lotus/Types/Sentinels/SentinelWeapons/SentBioWeapon": "Stinger",
  "/Lotus/Types/Sentinels/SentinelWeapons/SentElecRailgun": "Vulklok",
  "/Lotus/Types/Sentinels/SentinelWeapons/SentGlaiveWeapon": "Deconstructor",
  "/Lotus/Types/Sentinels/SentinelWeapons/SentShotgun": "Sweeper",
  "/Lotus/Types/Sentinels/SentinelWeapons/SentinelFreezeRayPrimeRifle": "Verglas Prime",
  "/Lotus/Types/Sentinels/SentinelWeapons/SentinelFreezeRayRifle": "Verglas",
  "/Lotus/Types/Vehicles/Hoverboard/HoverboardParts/PartComponents/HoverboardCorpusA/HoverboardCorpusADeck": "Flatbelly",
  "/Lotus/Types/Vehicles/Hoverboard/HoverboardParts/PartComponents/HoverboardCorpusB/HoverboardCorpusBDeck": "Needlenose",
  "/Lotus/Types/Vehicles/Hoverboard/HoverboardParts/PartComponents/HoverboardCorpusC/HoverboardCorpusCDeck": "Runway",
  "/Lotus/Types/Vehicles/Hoverboard/HoverboardParts/PartComponents/HoverboardInfestedB/HoverboardInfestedBDeck": "Feverspine",
  "/Lotus/Types/Vehicles/Hoverboard/HoverboardParts/PartComponents/HoverboardSolarisA/HoverboardSolarisADeck": "Bad Baby",
  "/Lotus/Weapons/Archon/Melee/DualDaggers/ArchonDualDaggersPlayerWep": "Nepheri",
  "/Lotus/Weapons/Archon/Melee/Trident/ArchonTridentPlayerWep": "Korumm",
  "/Lotus/Weapons/Archon/Melee/Whip/ArchonWhipPlayerWep": "Verdilac",
  "/Lotus/Weapons/Cephalon/Melee/Hammer/CephHammerWeapon": "Heliocor",
  "/Lotus/Weapons/Cephalon/Primary/CephPrimary/CephPrimary": "Simulor",
  "/Lotus/Weapons/ClanTech/Bio/AcidDartPistol": "Acrid",
  "/Lotus/Weapons/ClanTech/Bio/BioWeapon": "Torid",
  "/Lotus/Weapons/ClanTech/Chemical/FlameThrower": "Ignis",
  "/Lotus/Weapons/ClanTech/Chemical/FlameThrowerWraith": "Ignis Wraith",
  "/Lotus/Weapons/ClanTech/Chemical/RocketLauncher": "Ogris",
  "/Lotus/Weapons/ClanTech/Energy/CrpHeavyRifle": "Supra",
  "/Lotus/Weapons/ClanTech/Energy/CrpLaserPistol": "Spectra",
  "/Lotus/Weapons/ClanTech/Energy/CrpLaserRifle": "Flux Rifle",
  "/Lotus/Weapons/ClanTech/Energy/DeraVandal": "Dera Vandal",
  "/Lotus/Weapons/ClanTech/Energy/ElectroProd": "Prova",
  "/Lotus/Weapons/ClanTech/Energy/EnergyRifle": "Dera",
  "/Lotus/Weapons/ClanTech/Energy/Railgun": "Lanka",
  "/Lotus/Weapons/ClanTech/Energy/VandalElectroProd": "Prova Vandal",
  "/Lotus/Weapons/Corpus/BoardExec/Primary/CrpBEArcaPlasmor/CrpBEArcaPlasmor": "Tenet Arca Plasmor",
  "/Lotus/Weapons/Corpus/BoardExec/Primary/CrpBEFerrox/CrpBEFerrox": "Tenet Ferrox",
  "/Lotus/Weapons/Corpus/BoardExec/Primary/CrpBEFluxRifle/CrpBEFluxRifle": "Tenet Flux Rifle",
  "/Lotus/Weapons/Corpus/BoardExec/Primary/CrpBEGlaxion/CrpBEGlaxion": "Tenet Glaxion",
  "/Lotus/Weapons/Corpus/BoardExec/Primary/CrpBEQuanta/CrpBEQuanta": "Tenet Quanta",
  "/Lotus/Weapons/Corpus/BoardExec/Primary/CrpBETetra/CrpBETetra": "Tenet Tetra",
  "/Lotus/Weapons/Corpus/BoardExec/Secondary/CrpBECycron/CrpBECycron": "Tenet Cycron",
  "/Lotus/Weapons/Corpus/BoardExec/Secondary/CrpBEDetron/CrpBEDetron": "Tenet Detron",
  "/Lotus/Weapons/Corpus/BoardExec/Secondary/CrpBEPlinx/CrpBEPlinxWeapon": "Tenet Plinx",
  "/Lotus/Weapons/Corpus/Bow/Longbow/CrpBow": "Lenz",
  "/Lotus/Weapons/Corpus/Bow/Longbow/PrismaLenz/PrismaLenzWeapon": "Prisma Lenz",
  "/Lotus/Weapons/Corpus/LongGuns/ChainLightningGun/ChainLightningRifle": "Amprex",
  "/Lotus/Weapons/Corpus/LongGuns/CorpusUMP/CorpusUMP": "Tetra",
  "/Lotus/Weapons/Corpus/LongGuns/CorpusUMP/PrismaCorpusUMP": "Prisma Tetra",
  "/Lotus/Weapons/Corpus/LongGuns/CrpArSniper/CrpArSniperRifle": "Ambassador",
  "/Lotus/Weapons/Corpus/LongGuns/CrpBFG/CrpBFG": "Opticor",
  "/Lotus/Weapons/Corpus/LongGuns/CrpBFG/Vandal/VandalCrpBFG": "Opticor Vandal",
  "/Lotus/Weapons/Corpus/LongGuns/CrpBriefcaseLauncher/CrpBriefcaseLauncher": "Tenet Envoy",
  "/Lotus/Weapons/Corpus/LongGuns/CrpFreezeRay/CrpFreezeRayRifle": "Glaxion",
  "/Lotus/Weapons/Corpus/LongGuns/CrpFreezeRay/Vandal/CrpFreezeRayVandalRifle": "Glaxion Vandal",
  "/Lotus/Weapons/Corpus/LongGuns/CrpRubanRifle/CrpRubanRifle": "Stahlta",
  "/Lotus/Weapons/Corpus/LongGuns/CrpSentAmlgSniper/CrpSentAmlgSniper": "Komorex",
  "/Lotus/Weapons/Corpus/LongGuns/CrpSentExperimentRifle/CrpSentExperimentRifle": "Battacor",
  "/Lotus/Weapons/Corpus/LongGuns/CrpShapeBlast/CrpShapeBlastShotgun": "Exergis",
  "/Lotus/Weapons/Corpus/LongGuns/CrpShockRifle/CrpShockRifle": "Quanta",
  "/Lotus/Weapons/Corpus/LongGuns/CrpShockRifle/QuantaVandal": "Quanta Vandal",
  "/Lotus/Weapons/Corpus/LongGuns/CrpShotgun/CrpShotgun": "Arca Plasmor",
  "/Lotus/Weapons/Corpus/LongGuns/CrpSplitLaser/CrpSplitLaser": "Convectrix",
  "/Lotus/Weapons/Corpus/LongGuns/GrenadeLauncher/CarminePenta": "Carmine Penta",
  "/Lotus/Weapons/Corpus/LongGuns/GrenadeLauncher/GrenadeLauncher": "Penta",
  "/Lotus/Weapons/Corpus/LongGuns/Machinegun/SupraVandal": "Supra Vandal",
  "/Lotus/Weapons/Corpus/LongGuns/Spears/Railgun/CorpusRailgun": "Ferrox",
  "/Lotus/Weapons/Corpus/Melee/CrpBriefcase2HKatana/CrpBriefcase2HKatana": "Tenet Livia",
  "/Lotus/Weapons/Corpus/Melee/CrpBriefcaseScythe/CrpBriefcaseScythe": "Tenet Grigori",
  "/Lotus/Weapons/Corpus/Melee/CrpTonfa/CrpPrismaTonfa": "Prisma Ohma",
  "/Lotus/Weapons/Corpus/Melee/CrpTonfa/CrpTonfa": "Ohma",
  "/Lotus/Weapons/Corpus/Melee/CrpVenusHatchet/CrpVenusHatchet": "Kreska",
  "/Lotus/Weapons/Corpus/Melee/Glaive/CrpGhostCatcherGlaive/CrpGhostCatcherGlaive": "Xoris",
  "/Lotus/Weapons/Corpus/Melee/Glaive/CrpGlaive/CrpGlaive": "Falcor",
  "/Lotus/Weapons/Corpus/Melee/Gunblade/CrpGunBlade/CrpGunbladeWeapon": "Stropha",
  "/Lotus/Weapons/Corpus/Melee/Hammer/CorpusHammerWeapon": "Arca Titron",
  "/Lotus/Weapons/Corpus/Melee/KickAndPunch/KickPunchWeapon": "Obex",
  "/Lotus/Weapons/Corpus/Melee/KickAndPunch/PrismaObex": "Prisma Obex",
  "/Lotus/Weapons/Corpus/Melee/Polearm/CorpusPolearm01/CorpusPolearmWeapon": "Serro",
  "/Lotus/Weapons/Corpus/Melee/ShieldAndSword/CrpHammerShield/CrpHammerShield": "Tenet Agendus",
  "/Lotus/Weapons/Corpus/Melee/Whip/CorpusWhipWeapon": "Lecta",
  "/Lotus/Weapons/Corpus/Melee/Whips/CrpShockGrip/CrpShockGripWhipWeapon": "Galvacord",
  "/Lotus/Weapons/Corpus/Pistols/CorpusHandShotgun/CorpusHandCannon": "Detron",
  "/Lotus/Weapons/Corpus/Pistols/CorpusMinigun/CorpusMinigun": "Cestra",
  "/Lotus/Weapons/Corpus/Pistols/CorpusMinigun/DualCorpusMinigun": "Dual Cestra",
  "/Lotus/Weapons/Corpus/Pistols/CorpusModularPistol/Vandal/CrpLaserPistolVandal": "Spectra Vandal",
  "/Lotus/Weapons/Corpus/Pistols/CrpAirPistol/CrpAirPistolArray": "Sonicor",
  "/Lotus/Weapons/Corpus/Pistols/CrpBriefcaseAkimbo/CrpBriefcaseAkimboPistol": "Tenet Diplos",
  "/Lotus/Weapons/Corpus/Pistols/CrpChargeGun/CrpChargeGun": "Cycron",
  "/Lotus/Weapons/Corpus/Pistols/CrpElectroMag/CrpElectroMag": "Staticor",
  "/Lotus/Weapons/Corpus/Pistols/CrpHandRL/CorpusHandRocketLauncher": "Angstrum",
  "/Lotus/Weapons/Corpus/Pistols/CrpHandRL/PrismaAngstrum": "Prisma Angstrum",
  "/Lotus/Weapons/Corpus/Pistols/CrpIgniterPistol/CrpIgniterPistol": "Tenet Spirex",
  "/Lotus/Weapons/Corpus/Pistols/CrpSentAmalgPistol/CrpSentAmalgPistol": "Cyanex",
  "/Lotus/Weapons/Corpus/Pistols/CrpSentExperimentPistol/CrpSentExperimentPistol": "Ocucor",
  "/Lotus/Weapons/Corpus/Pistols/CrpSonificBlastor/CrpBlastorWeapon": "Plinx",
  "/Lotus/Weapons/Corpus/Pistols/SniperPistol/CrpScopeGun": "Arca Scisco",
  "/Lotus/Weapons/Grineer/Bows/GrnBow/GrnBowWeapon": "Kuva Bramma",
  "/Lotus/Weapons/Grineer/GrineerPistol/GrineerAkimboPistol": "Twin Gremlins",
  "/Lotus/Weapons/Grineer/GrineerPistol/GrineerLightPistol": "Viper",
  "/Lotus/Weapons/Grineer/GrineerPistol/GrnHeavyPistol": "Kraken",
  "/Lotus/Weapons/Grineer/GrineerPistol/GrnScopedPistolPlayer": "Seer",
  "/Lotus/Weapons/Grineer/HeavyWeapons/GrnHeavyGrenadeLauncher": "Kuva Ayanga",
  "/Lotus/Weapons/Grineer/KuvaLich/HeavyWeapons/Grattler/KuvaGrattler": "Kuva Grattler",
  "/Lotus/Weapons/Grineer/KuvaLich/LongGuns/Drakgoon/KuvaDrakgoon": "Kuva Drakgoon",
  "/Lotus/Weapons/Grineer/KuvaLich/LongGuns/Hek/KuvaHekWeapon": "Kuva Hek",
  "/Lotus/Weapons/Grineer/KuvaLich/LongGuns/Hind/KuvaHind": "Kuva Hind",
  "/Lotus/Weapons/Grineer/KuvaLich/LongGuns/Karak/KuvaKarak": "Kuva Karak",
  "/Lotus/Weapons/Grineer/KuvaLich/LongGuns/Kohm/KuvaKohm": "Kuva Kohm",
  "/Lotus/Weapons/Grineer/KuvaLich/LongGuns/Ogris/KuvaOgris": "Kuva Ogris",
  "/Lotus/Weapons/Grineer/KuvaLich/LongGuns/Quartakk/KuvaQuartakk": "Kuva Quartakk",
  "/Lotus/Weapons/Grineer/KuvaLich/LongGuns/Sobek/KuvaSobek": "Kuva Sobek",
  "/Lotus/Weapons/Grineer/KuvaLich/LongGuns/Tonkor/KuvaTonkor": "Kuva Tonkor",
  "/Lotus/Weapons/Grineer/KuvaLich/LongGuns/Zarr/KuvaZarr": "Kuva Zarr",
  "/Lotus/Weapons/Grineer/KuvaLich/Melee/Ghoulsaw/KuvaGhoulSaw": "Kuva Ghoulsaw",
  "/Lotus/Weapons/Grineer/KuvaLich/Secondaries/Brakk/KuvaBrakk": "Kuva Brakk",
  "/Lotus/Weapons/Grineer/KuvaLich/Secondaries/Kraken/KuvaKraken": "Kuva Kraken",
  "/Lotus/Weapons/Grineer/KuvaLich/Secondaries/Nukor/KuvaNukor": "Kuva Nukor",
  "/Lotus/Weapons/Grineer/KuvaLich/Secondaries/Seer/KuvaSeer": "Kuva Seer",
  "/Lotus/Weapons/Grineer/KuvaLich/Secondaries/Stubba/KuvaStubba": "Kuva Twin Stubbas",
  "/Lotus/Weapons/Grineer/LongGuns/BurstRifle/GrnBurstRifle": "Hind",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerAssaultRifle/GrnAssaultRifle": "Grakata",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerAssaultRifle/TwinGrakatas": "Twin Grakatas",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerFlakCannon/FlakCannon": "Drakgoon",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerLeverActionRifle/GLARifle": "Grinlok",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerLeverActionRifle/PrismaGrinlokWeapon": "Prisma Grinlok",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerM16Homage/GrineerM16Rifle": "Karak",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerM16Homage/KarakWraith": "Karak Wraith",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerSawbladeGun/SawBladeGun": "Miter",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerSniperRifle/GrnSniperRifle": "Vulkar",
  "/Lotus/Weapons/Grineer/LongGuns/GrineerSniperRifle/VulkarWraith": "Vulkar Wraith",
  "/Lotus/Weapons/Grineer/LongGuns/GrnCannon/GrnCannonWeapon": "Zarr",
  "/Lotus/Weapons/Grineer/LongGuns/GrnFlameSpear/GrnFlameSpear": "Javlok",
  "/Lotus/Weapons/Grineer/LongGuns/GrnFourBarrelRifle/GrnFourBarrelRifleWeapon": "Quartakk",
  "/Lotus/Weapons/Grineer/LongGuns/GrnGorgSniperRifle/GrnGorgSniperRifle": "Buzlok",
  "/Lotus/Weapons/Grineer/LongGuns/GrnGrenadeLauncher/GrnGrenadeLauncher": "Tonkor",
  "/Lotus/Weapons/Grineer/LongGuns/GrnHarpoonGun/GrnHarpoonGun": "Harpak",
  "/Lotus/Weapons/Grineer/LongGuns/GrnKuvaLichRifle/GrnKuvaLichRifleWeapon": "Kuva Chakkhurr",
  "/Lotus/Weapons/Grineer/LongGuns/GrnOrokinRifle/GrnOrokinRifleWeapon": "Gotva Prime",
  "/Lotus/Weapons/Grineer/LongGuns/GrnSpark/GrnSparkRifle": "Kohm",
  "/Lotus/Weapons/Grineer/LongGuns/LaserAimRifle/LaserAimRifle": "Argonak",
  "/Lotus/Weapons/Grineer/LongGuns/VoidTraderGorgon/VTGorgon": "Prisma Gorgon",
  "/Lotus/Weapons/Grineer/LongGuns/WraithGorgon/WraithGorgon": "Gorgon Wraith",
  "/Lotus/Weapons/Grineer/Melee/GrineerClaws/GrnClaws": "Ripkas",
  "/Lotus/Weapons/Grineer/Melee/GrineerCombatKnife/GrineerCombatKnife": "Sheev",
  "/Lotus/Weapons/Grineer/Melee/GrineerHalberd/GrnHalberd": "Kesheg",
  "/Lotus/Weapons/Grineer/Melee/GrineerJetPoweredPolearm/GrineerJetPolearm": "Jat Kittag",
  "/Lotus/Weapons/Grineer/Melee/GrineerMachetteAndCleaver/DualCleaverWeapon": "Dual Cleavers",
  "/Lotus/Weapons/Grineer/Melee/GrineerMachetteAndCleaver/Machete": "Machete",
  "/Lotus/Weapons/Grineer/Melee/GrineerMachetteAndCleaver/PrismaDualCleavers": "Prisma Dual Cleavers",
  "/Lotus/Weapons/Grineer/Melee/GrineerMachetteAndCleaver/PrismaMachete": "Prisma Machete",
  "/Lotus/Weapons/Grineer/Melee/GrineerMachetteAndCleaver/WraithMacheteWeapon": "Machete Wraith",
  "/Lotus/Weapons/Grineer/Melee/GrineerTylAxeAndBoar/RegorAxeShield": "Ack & Brunt",
  "/Lotus/Weapons/Grineer/Melee/GrineerWhip/GrineerWhip": "Atterax",
  "/Lotus/Weapons/Grineer/Melee/GrnBoomerang/GrnBoomerang": "Halikar",
  "/Lotus/Weapons/Grineer/Melee/GrnBoomerang/HalikarWraithWeapon": "Halikar Wraith",
  "/Lotus/Weapons/Grineer/Melee/GrnDualFireAxe/GrnDualFireAxe": "Twin Basolk",
  "/Lotus/Weapons/Grineer/Melee/GrnEgyptSwd/DualGrnEgyptSwdWeapon": "Twin Krohkur",
  "/Lotus/Weapons/Grineer/Melee/GrnEgyptSwd/GrnEgyptSwdWeapon": "Krohkur",
  "/Lotus/Weapons/Grineer/Melee/GrnGhoulSaw/GrnGhoulSawPlayer": "Ghoulsaw",
  "/Lotus/Weapons/Grineer/Melee/GrnKusarigama/GrnKusarigamaWeapon": "Jat Kusar",
  "/Lotus/Weapons/Grineer/Melee/GrnKuvaLichScythe/GrnKuvaLichScytheWeapon": "Kuva Shildeg",
  "/Lotus/Weapons/Grineer/Melee/GrnQueenSceptre/GrnQueenSceptreWeapon": "Broken Scepter",
  "/Lotus/Weapons/Grineer/Melee/GrnSharbola/GrnSharbolaWeapon": "Slaytra",
  "/Lotus/Weapons/Grineer/Melee/GrnSparring/GrnSpiderSparring/GrnSpiderSparring": "Korrudo",
  "/Lotus/Weapons/Grineer/Melee/GrnTrident/GrnTridentWeapon": "Sydon",
  "/Lotus/Weapons/Grineer/Melee/GunBlade/GrnGunBlade/GrnGunblade": "Vastilok",
  "/Lotus/Weapons/Grineer/Melee/Scythe/GrnDrillScythe/GrnDrillScythe": "Galariak Prime",
  "/Lotus/Weapons/Grineer/Melee/Tonfa/GrnChainSawTonfa/GrnChainSawTonfaWeapon": "Tonkkatt",
  "/Lotus/Weapons/Grineer/Pistols/GrineerBulbousSMG/Prisma/PrismaTwinGremlinsWeapon": "Prisma Twin Gremlins",
  "/Lotus/Weapons/Grineer/Pistols/GrineerCrossbow/GrineerGooGun": "Stug",
  "/Lotus/Weapons/Grineer/Pistols/GrineerHandShotgun/GrineerHandCannon": "Brakk",
  "/Lotus/Weapons/Grineer/Pistols/GrineerLeverActionPistol/GLAPistol": "Marelok",
  "/Lotus/Weapons/Grineer/Pistols/GrineerMicrowavegun/GrnMicrowavePistol": "Nukor",
  "/Lotus/Weapons/Grineer/Pistols/GrnAmphisPistol/GrnAmphisPistol": "Quatz",
  "/Lotus/Weapons/Grineer/Pistols/GrnDWUniques/GrnTwinKohmaks": "Twin Kohmak",
  "/Lotus/Weapons/Grineer/Pistols/GrnKohmPistol/GrnKohmPistol": "Kohmak",
  "/Lotus/Weapons/Grineer/Pistols/GrnOrokinPistol/GrnOrokinPistol": "Sagek Prime",
  "/Lotus/Weapons/Grineer/Pistols/GrnQueenGuardDualPistol/GrnQueenGuardDualPistols": "Twin Rogga",
  "/Lotus/Weapons/Grineer/Pistols/GrnTorpedoPistol/GrnTorpedoPistol": "Kulstar",
  "/Lotus/Weapons/Grineer/Pistols/GrnUzi/GrnUziWeapon": "Stubba",
  "/Lotus/Weapons/Grineer/Pistols/HeatGun/GrnHeatGun": "Atomos",
  "/Lotus/Weapons/Grineer/Pistols/WraithSingleViper/WraithSingleViper": "Viper Wraith",
  "/Lotus/Weapons/Grineer/Pistols/WraithTwinVipers/WraithTwinVipers": "Twin Vipers Wraith",
  "/Lotus/Weapons/Grineer/ThrowingWeapons/GrnVorStickyBomb/GrnVorStickyBomb": "Aegrit",
  "/Lotus/Weapons/Infested/Bow/InfCernosBow/InfCernos": "Mutalist Cernos",
  "/Lotus/Weapons/Infested/InfestedLich/LongGuns/1999InfShotgun/1999InfShotgunWeapon": "Coda Bassocyst",
  "/Lotus/Weapons/Infested/InfestedLich/LongGuns/CodaBubonico/CodaBubonicoCannon": "Coda Bubonico",
  "/Lotus/Weapons/Infested/InfestedLich/LongGuns/CodaHema": "Coda Hema",
  "/Lotus/Weapons/Infested/InfestedLich/LongGuns/CodaSporothrix": "Coda Sporothrix",
  "/Lotus/Weapons/Infested/InfestedLich/LongGuns/CodaSynapse": "Coda Synapse",
  "/Lotus/Weapons/Infested/InfestedLich/Melee/CodaCaustacyst/CodaCaustacyst": "Coda Caustacyst",
  "/Lotus/Weapons/Infested/InfestedLich/Melee/CodaHirudo": "Coda Hirudo",
  "/Lotus/Weapons/Infested/InfestedLich/Melee/CodaMire": "Coda Mire",
  "/Lotus/Weapons/Infested/InfestedLich/Melee/CodaPathocyst/CodaPathocyst": "Coda Pathocyst",
  "/Lotus/Weapons/Infested/InfestedLich/Melee/InfestedHammer/InfLichHammerWeapon": "Coda Motovore",
  "/Lotus/Weapons/Infested/InfestedLich/Pistols/1999InfSporePistol/1999InfSporePistolWeapon": "Dual Coda Torxica",
  "/Lotus/Weapons/Infested/InfestedLich/Pistols/CodaCatabolyst": "Coda Catabolyst",
  "/Lotus/Weapons/Infested/InfestedLich/Pistols/CodaPox": "Coda Pox",
  "/Lotus/Weapons/Infested/InfestedLich/Pistols/CodaTysis": "Coda Tysis",
  "/Lotus/Weapons/Infested/LongGuns/InfArmCannon/InfArmCannon": "Bubonico",
  "/Lotus/Weapons/Infested/LongGuns/InfCrpShockSwarm/InfCrpShockSwarmRifle": "Mutalist Quanta",
  "/Lotus/Weapons/Infested/LongGuns/InfSniperRifle/InfSniperRifle": "Sporothrix",
  "/Lotus/Weapons/Infested/LongGuns/InfWFAccompanyingPri/InfestedBurstRifle": "Hema",
  "/Lotus/Weapons/Infested/LongGuns/InfestedRifle": "Synapse",
  "/Lotus/Weapons/Infested/LongGuns/QuantaFullyInfested/InfQuantaRifle": "Paracyst",
  "/Lotus/Weapons/Infested/LongGuns/Tentacluster/InfestedShotgun": "Phage",
  "/Lotus/Weapons/Infested/Melee/Glaives/PunctureGlaive/PunctureGlaiveWeapon": "Cerata",
  "/Lotus/Weapons/Infested/Melee/InfBoomerang/InfBoomerangWeapon": "Pathocyst",
  "/Lotus/Weapons/Infested/Melee/InfEmbolistScythe/InfestedScythe": "Caustacyst",
  "/Lotus/Weapons/Infested/Melee/InfTransformClaw/InfTransformClawsWeapon": "Keratinos",
  "/Lotus/Weapons/Infested/Melee/InfWFAccompanyingSparring/InfestedKogake": "Hirudo",
  "/Lotus/Weapons/Infested/Melee/InfWarfan/InfWarfanWeapon": "Arum Spinosa",
  "/Lotus/Weapons/Infested/Melee/Nunchaku/InfNunchuck/InfNunchuck": "Pulmonars",
  "/Lotus/Weapons/Infested/Melee/Staff/InfStaff/InfStaff": "Pupacyst",
  "/Lotus/Weapons/Infested/Melee/Swords/Mios/Mios": "Mios",
  "/Lotus/Weapons/Infested/Melee/Swords/Mire/MireSword": "Mire",
  "/Lotus/Weapons/Infested/Melee/TipedoStaff/InfTipedoStaff": "Lesion",
  "/Lotus/Weapons/Infested/Melee/Whip/InfestedWhip/InfestedWhipWeapon": "Scoliac",
  "/Lotus/Weapons/Infested/Pistols/InfBeamPistol/InfBeamPistol": "Catabolyst",
  "/Lotus/Weapons/Infested/Pistols/InfProximityStars/InfProximityStars": "Pox",
  "/Lotus/Weapons/Infested/Pistols/InfUzi/InfUziWeapon": "Zymos",
  "/Lotus/Weapons/Infested/Pistols/InfVomitGun/InfVomitGunWep": "Dual Toxocyst",
  "/Lotus/Weapons/Infested/Pistols/InfestedDartPistol/InfestedDartPistol": "Tysis",
  "/Lotus/Weapons/Infested/Pistols/InfestedPistol": "Embolist",
  "/Lotus/Weapons/Lasria/AK47/TC2024AK47Weapon": "Ax-52",
  "/Lotus/Weapons/Lasria/LasGooAK/LasGooAKPlayerWeapon": "Efv-5 Jupiter",
  "/Lotus/Weapons/Lasria/LasGooPistol/LasGooPistolPlayerWeapon": "Efv-8 Mars",
  "/Lotus/Weapons/Lasria/LasGooSickle/LasGooSicklePlayerWeapon": "Dual Viciss",
  "/Lotus/Weapons/Lasria/LasGrenadeLauncher/LasrianNoxPlayerWeapon": "Purgator 1",
  "/Lotus/Weapons/Lasria/LasSilencedPistol/LasSilencedPistolWeapon": "Vesper 77",
  "/Lotus/Weapons/MK1Series/MK1Bo": "Mk1-Bo",
  "/Lotus/Weapons/MK1Series/MK1Furax": "Mk1-Furax",
  "/Lotus/Weapons/MK1Series/MK1Furis": "Mk1-Furis",
  "/Lotus/Weapons/MK1Series/MK1Kunai": "Mk1-Kunai",
  "/Lotus/Weapons/MK1Series/MK1Paris": "Mk1-Paris",
  "/Lotus/Weapons/MK1Series/MK1Strun": "Mk1-Strun",
  "/Lotus/Weapons/Operator/Melee/DrifterTazer/DrifterTazerPlayerWep": "Rumblejack",
  "/Lotus/Weapons/Operator/Pistols/DrifterPistol/DrifterPistolPlayerWeapon": "Sirocco",
  "/Lotus/Weapons/Orokin/BallasSword/BallasSwordWeapon": "Paracesis",
  "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipFive": "Dehtat",
  "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipFour": "Cyath",
  "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipOne": "Balla",
  "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipSix": "Kronsh",
  "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipThree": "Mewan",
  "/Lotus/Weapons/Ostron/Melee/ModularMelee01/Tip/TipTwo": "Ooltha",
  "/Lotus/Weapons/Ostron/Melee/ModularMelee02/Tip/TipEleven": "Dokrahm",
  "/Lotus/Weapons/Ostron/Melee/ModularMelee02/Tip/TipNine": "Sepfahn",
  "/Lotus/Weapons/Ostron/Melee/ModularMelee02/Tip/TipTen": "Rabvee",
  "/Lotus/Weapons/Ostron/Melee/ModularMeleeInfested/Tips/InfestedTipOne": "Plague Kripath",
  "/Lotus/Weapons/Ostron/Melee/ModularMeleeInfested/Tips/InfestedTipTwo": "Plague Keewar",
  "/Lotus/Weapons/Sentients/SentJointedScythe/SentJointedScytheWeapon": "Venato",
  "/Lotus/Weapons/Sentients/SentOctaMiniGun/SentOctaMiniGun": "Haalvu",
  "/Lotus/Weapons/Sentients/SentRifleNewWar/SentRifleNewWarGun": "Basmu",
  "/Lotus/Weapons/Sentients/Shedu/SheduHeavyWeapon": "Shedu",
  "/Lotus/Weapons/SolarisUnited/Secondary/SUModularSecondarySet1/Barrel/SUModularSecondaryBarrelAPart": "Catchmoon",
  "/Lotus/Weapons/SolarisUnited/Secondary/SUModularSecondarySet1/Barrel/SUModularSecondaryBarrelBPart": "Tombfinger",
  "/Lotus/Weapons/SolarisUnited/Secondary/SUModularSecondarySet1/Barrel/SUModularSecondaryBarrelCPart": "Rattleguts",
  "/Lotus/Weapons/SolarisUnited/Secondary/SUModularSecondarySet1/Barrel/SUModularSecondaryBarrelDPart": "Gaze",
  "/Lotus/Weapons/Syndicates/ArbitersOfHexis/LongGuns/AHBoltor": "Telos Boltor",
  "/Lotus/Weapons/Syndicates/ArbitersOfHexis/Melee/AHBoltace": "Telos Boltace",
  "/Lotus/Weapons/Syndicates/ArbitersOfHexis/Pistols/AHAkbolto": "Telos Akbolto",
  "/Lotus/Weapons/Syndicates/CephalonSuda/LongGuns/CSSimulor": "Synoid Simulor",
  "/Lotus/Weapons/Syndicates/CephalonSuda/Melee/CSHeliocor": "Synoid Heliocor",
  "/Lotus/Weapons/Syndicates/CephalonSuda/Pistols/CSDroidArray": "Gammacor",
  "/Lotus/Weapons/Syndicates/CephalonSuda/Pistols/CSSynoidGammacor": "Synoid Gammacor",
  "/Lotus/Weapons/Syndicates/NewLoka/LongGuns/NLTigris": "Sancti Tigris",
  "/Lotus/Weapons/Syndicates/NewLoka/Melee/NLMagistar": "Sancti Magistar",
  "/Lotus/Weapons/Syndicates/NewLoka/Pistols/NLCastanas": "Sancti Castanas",
  "/Lotus/Weapons/Syndicates/PerrinSequence/LongGuns/PSPenta": "Secura Penta",
  "/Lotus/Weapons/Syndicates/PerrinSequence/Melee/PSLecta": "Secura Lecta",
  "/Lotus/Weapons/Syndicates/PerrinSequence/Pistols/PSDualCestra": "Secura Dual Cestra",
  "/Lotus/Weapons/Syndicates/RedVeil/Bows/RVCernos": "Rakta Cernos",
  "/Lotus/Weapons/Syndicates/RedVeil/Melee/RVDarkDagger": "Rakta Dark Dagger",
  "/Lotus/Weapons/Syndicates/RedVeil/Pistols/RVBallistica": "Rakta Ballistica",
  "/Lotus/Weapons/Syndicates/SteelMeridian/LongGuns/SMHek": "Vaykor Hek",
  "/Lotus/Weapons/Syndicates/SteelMeridian/Melee/SMSydon": "Vaykor Sydon",
  "/Lotus/Weapons/Syndicates/SteelMeridian/Pistols/SMMarelok": "Vaykor Marelok",
  "/Lotus/Weapons/Tenno/Akimbo/AkLexPistols": "Aklex",
  "/Lotus/Weapons/Tenno/Akimbo/AkLexPrimePistols": "Aklex Prime",
  "/Lotus/Weapons/Tenno/Akimbo/AkimboAutoPistols": "Afuris",
  "/Lotus/Weapons/Tenno/Akimbo/AkimboBolto": "Akbolto",
  "/Lotus/Weapons/Tenno/Akimbo/AkimboPistol": "Aklato",
  "/Lotus/Weapons/Tenno/Akimbo/AkimboShotGun": "Akbronco",
  "/Lotus/Weapons/Tenno/Akimbo/AkimboViperPistols": "Twin Vipers",
  "/Lotus/Weapons/Tenno/Akimbo/DualMagnus": "Akmagnus",
  "/Lotus/Weapons/Tenno/Akimbo/DualMagnusPrime": "Akmagnus Prime",
  "/Lotus/Weapons/Tenno/Akimbo/DualVastos": "Akvasto",
  "/Lotus/Weapons/Tenno/Akimbo/PrimeAkimboShotGun": "Akbronco Prime",
  "/Lotus/Weapons/Tenno/Archwing/Melee/ArchHammer/ArchHammer": "Rathbone",
  "/Lotus/Weapons/Tenno/Archwing/Melee/ArchScythe/ArchScythe": "Kaszas",
  "/Lotus/Weapons/Tenno/Archwing/Melee/ArchSwordHook/ArchHookSwordWeapon": "Agkuza",
  "/Lotus/Weapons/Tenno/Archwing/Melee/Archaxe/ArchAxeWeapon": "Onorix",
  "/Lotus/Weapons/Tenno/Archwing/Melee/Archsword/ArchSwordWeapon": "Veritux",
  "/Lotus/Weapons/Tenno/Archwing/Melee/Archswordandshield/ArchSwordShield": "Centaur",
  "/Lotus/Weapons/Tenno/Archwing/Melee/ExaltedArchScythe/ExaltedAWScytheWeapon": "Corufell",
  "/Lotus/Weapons/Tenno/Archwing/Melee/GrnArchHand/GrnArchHandWeapon": "Knux",
  "/Lotus/Weapons/Tenno/Archwing/Melee/VoidTraderArchsword/VTArchSwordWeapon": "Prisma Veritux",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ArchBurstGun/ArchBurstGun": "Cyngas",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ArchLongRifle/ArchLongRifle": "Phaedra",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ArchwingHeavyPistols/ArchHeavyPistols": "Dual Decurion",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ArchwingHeavyPistols/Prisma/PrismaArchHeavyPistols": "Prisma Dual Decurions",
  "/Lotus/Weapons/Tenno/Archwing/Primary/FoldingMachineGun/ArchMachineGun": "Imperator",
  "/Lotus/Weapons/Tenno/Archwing/Primary/FoldingMachineGun/ArchMachineGunVandal": "Imperator Vandal",
  "/Lotus/Weapons/Tenno/Archwing/Primary/LaunchGrenade/ArchCannon": "Corvas",
  "/Lotus/Weapons/Tenno/Archwing/Primary/NokkoArchGun/NokkoArchGun": "Arbucep",
  "/Lotus/Weapons/Tenno/Archwing/Primary/PrimeCorvas/PrimeCorvasWeapon": "Corvas Prime",
  "/Lotus/Weapons/Tenno/Archwing/Primary/PrimeLarkspur/PrimeLarkspurWeapon": "Larkspur Prime",
  "/Lotus/Weapons/Tenno/Archwing/Primary/Railgun/ArchRailgun": "Velocitus",
  "/Lotus/Weapons/Tenno/Archwing/Primary/RepurposedGrineerAntiAircraftGun/ArchGRNAAGun": "Grattler",
  "/Lotus/Weapons/Tenno/Archwing/Primary/RocketArtillery/ArchRocketCrossbow": "Fluctus",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ThanoTechArchGun/ThanoTechArchGun": "Cortege",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ThanoTechArchLongGun/ThanoTechLongGun": "Mausolon",
  "/Lotus/Weapons/Tenno/Archwing/Primary/ThanoTechGrenadeLaunch/ThanoTechGrenadeLauncher": "Morgha",
  "/Lotus/Weapons/Tenno/Archwing/Primary/TnConcreteArchgun/TnConcreteArchgunWeapon": "Mandonel",
  "/Lotus/Weapons/Tenno/Archwing/Primary/TnShieldframeArchGun/TnShieldFrameArchGun": "Larkspur",
  "/Lotus/Weapons/Tenno/Bayonet/TnBayonetRifleWeapon": "Vinquibus",
  "/Lotus/Weapons/Tenno/Bows/AntlerBow/AntlerBow": "Cernos",
  "/Lotus/Weapons/Tenno/Bows/AsymetricalBow/AsymetricalBow": "Daikyu",
  "/Lotus/Weapons/Tenno/Bows/DaxDuviriAsymetricalBow/DaxDuviriAsymmetricalLongBowPlayerWeapon": "Cinta",
  "/Lotus/Weapons/Tenno/Bows/HuntingBow": "Paris",
  "/Lotus/Weapons/Tenno/Bows/Omicrus/OmicrusPlayerWep": "Nataruk",
  "/Lotus/Weapons/Tenno/Bows/PrimeCernos/PrimeCernos": "Cernos Prime",
  "/Lotus/Weapons/Tenno/Bows/PrimeDaikyu/PrimeDaikyuBow": "Daikyu Prime",
  "/Lotus/Weapons/Tenno/Bows/PrimeDerelictCernos/DerelictCernos": "Proboscis Cernos",
  "/Lotus/Weapons/Tenno/Bows/PrimeHuntingBow": "Paris Prime",
  "/Lotus/Weapons/Tenno/Bows/StalkerBow": "Dread",
  "/Lotus/Weapons/Tenno/Bows/TnChoirBow/TnChoirBow": "Evensong",
  "/Lotus/Weapons/Tenno/Grimoire/TnDoppelgangerGrimoire": "Grimoire",
  "/Lotus/Weapons/Tenno/Grimoire/TnGrimoire": "Grimoire",
  "/Lotus/Weapons/Tenno/LongGuns/DexTheThird/DexTheThird": "Dex Sybaris",
  "/Lotus/Weapons/Tenno/LongGuns/DoubleBarrelShotgun/TennoDoubleBarrelShotgun": "Tigris",
  "/Lotus/Weapons/Tenno/LongGuns/DrakeRifle/DrakeRifle": "Tiberon",
  "/Lotus/Weapons/Tenno/LongGuns/FiveShotSniper/FiveShotSniper": "Rubico",
  "/Lotus/Weapons/Tenno/LongGuns/GarudaCrossbow/GarudaCrossbow": "Nagantaka",
  "/Lotus/Weapons/Tenno/LongGuns/Gunbrella/ShrineMaidenGunbrellaWeapon": "Higasa",
  "/Lotus/Weapons/Tenno/LongGuns/GyreRifle/GyreRifleWeapon": "Alternox",
  "/Lotus/Weapons/Tenno/LongGuns/LoginPrimary/SundialRifle": "Zenith",
  "/Lotus/Weapons/Tenno/LongGuns/Miter/TnoMiter": "Panthera",
  "/Lotus/Weapons/Tenno/LongGuns/PaxDuviricusShotgun/PaxDuviricusShotgun": "Rauta",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeAcceltra/PrimeAcceltraWeapon": "Acceltra Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeAfentis/PrimeAfentisWeapon": "Afentis Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeAlternox/PrimeAlternoxWeapon": "Alternox Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeAstilla/AstillaPrimeWeapon": "Astilla Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeBaza/PrimeBazaGun": "Baza Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeBoltor/PrimeBoltor": "Boltor Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeBurston/PrimeBurston": "Burston Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeCedo/PrimeCedoWeapon": "Cedo Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeCorinth/PrimeCorinth": "Corinth Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeFulmin/PrimeFulmin": "Fulmin Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeLightningGun/PrimeLightningGun": "Vadarya Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeNagantaka/PrimeNagantakaWeapon": "Nagantaka Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimePanthera/PrimePanthera": "Panthera Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimePerigale/PrimePerigaleSniper": "Perigale Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimePhantasma/PhantasmaPrimeShotgun": "Phantasma Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeScourge/PrimeScourgeWeapon": "Scourge Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeSoma/PrimeSomaRifle": "Soma Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeStradavar/PrimeStradavarGun": "Stradavar Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeStrun/PrimeStrunWeapon": "Strun Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeSybaris/PrimeSybarisRifle": "Sybaris Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeTenora/TenoraPrimeWeapon": "Tenora Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeTiberon/PrimeTiberonRifle": "Tiberon Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeTigris/PrimeTigris": "Tigris Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeTrumna/PrimeTrumnaWeapon": "Trumna Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeVectis/PrimeVectisRifle": "Vectis Prime",
  "/Lotus/Weapons/Tenno/LongGuns/PrimeZhuge/PrimeZhugeCrossbow": "Zhuge Prime",
  "/Lotus/Weapons/Tenno/LongGuns/RepeatingCrossbow/RepeatingCrossbow": "Zhuge",
  "/Lotus/Weapons/Tenno/LongGuns/RevenantShotgun/RevenantShotgun": "Phantasma",
  "/Lotus/Weapons/Tenno/LongGuns/RubicoPrime/RubicoPrimeWeapon": "Rubico Prime",
  "/Lotus/Weapons/Tenno/LongGuns/SapientPrimary/SapientPrimaryWeapon": "Acceltra",
  "/Lotus/Weapons/Tenno/LongGuns/TennoTommyGun/TennoTommyGunRifle": "Stradavar",
  "/Lotus/Weapons/Tenno/LongGuns/TnAlchemistShotgun/TnAlchemistShotgun": "Cedo",
  "/Lotus/Weapons/Tenno/LongGuns/TnBardRifle/TnBardRifle": "Tenora",
  "/Lotus/Weapons/Tenno/LongGuns/TnBeltFedRifle/TnBeltFedRifleWeapon": "Reconifex",
  "/Lotus/Weapons/Tenno/LongGuns/TnGlassShotgun/TnGlassShotgunGun": "Astilla",
  "/Lotus/Weapons/Tenno/LongGuns/TnHeavyShotgun/TnHeavyShotgunGun": "Corinth",
  "/Lotus/Weapons/Tenno/LongGuns/TnHopliteSpear/TnHopliteSpearGunWeapon": "Afentis",
  "/Lotus/Weapons/Tenno/LongGuns/TnInkRifle/TnInkRifleWeapon": "Enkaus",
  "/Lotus/Weapons/Tenno/LongGuns/TnModQuestRifle/TnModQuestRifleWeapon": "Thornbak",
  "/Lotus/Weapons/Tenno/LongGuns/TnPriestSpear/TnPriestSpearGun": "Scourge",
  "/Lotus/Weapons/Tenno/LongGuns/TnQuadSniper/TnQuadSniper": "Perigale",
  "/Lotus/Weapons/Tenno/LongGuns/TnRailjackRifle/RailjackRifleGun": "Quellor",
  "/Lotus/Weapons/Tenno/LongGuns/TnRevolverRifle/TnRevolverRifleGun": "Veldt",
  "/Lotus/Weapons/Tenno/LongGuns/TnRifleErsatz/TnRifleErsatzWeapon": "Aeolak",
  "/Lotus/Weapons/Tenno/LongGuns/TnSMG/TnSMGWeapon": "Baza",
  "/Lotus/Weapons/Tenno/LongGuns/TnWispRifle/TnWispRifle": "Fulmin",
  "/Lotus/Weapons/Tenno/LongGuns/TnoLeverAction/TnoLeverActionRifle": "Sybaris",
  "/Lotus/Weapons/Tenno/LongGuns/TnoLotusPodShotgun/TnoLotusPodShotgun": "Steflos",
  "/Lotus/Weapons/Tenno/LongGuns/TnoPrmryXbow/TnoPrmryXbowWeapon": "Attica",
  "/Lotus/Weapons/Tenno/LongGuns/WraithLatron/WraithLatron": "Latron Wraith",
  "/Lotus/Weapons/Tenno/Melee/Axe/AxeWeapon": "Scindo",
  "/Lotus/Weapons/Tenno/Melee/Axe/DualAxeWeapon": "Dual Zoren",
  "/Lotus/Weapons/Tenno/Melee/Axe/DualInfestedAxesWeapon": "Dual Ichor",
  "/Lotus/Weapons/Tenno/Melee/Axe/PrimeScindo/PrimeScindoWeapon": "Scindo Prime",
  "/Lotus/Weapons/Tenno/Melee/Axe/PrimeVorunaAxeWeapon": "Sarofang Prime",
  "/Lotus/Weapons/Tenno/Melee/Axe/PrimeZoren/PrimeZorenAxeWeapon": "Dual Zoren Prime",
  "/Lotus/Weapons/Tenno/Melee/Axe/WolfFrameAxeWeapon": "Sarofang",
  "/Lotus/Weapons/Tenno/Melee/BrassKnuckles/BrassKnuckles": "Kogake",
  "/Lotus/Weapons/Tenno/Melee/Claws/TennoClaws": "Venka",
  "/Lotus/Weapons/Tenno/Melee/CronusSword/CronusLongSword": "Cronus",
  "/Lotus/Weapons/Tenno/Melee/CronusSword/PrimeCronusLongSword": "Dakra Prime",
  "/Lotus/Weapons/Tenno/Melee/Dagger/CeramicDagger": "Ceramic Dagger",
  "/Lotus/Weapons/Tenno/Melee/Dagger/Dagger": "Heat Dagger",
  "/Lotus/Weapons/Tenno/Melee/Dagger/DarkDagger": "Dark Dagger",
  "/Lotus/Weapons/Tenno/Melee/DualDagger/DualDagger": "Fang",
  "/Lotus/Weapons/Tenno/Melee/DualDagger/DualEtherDagger": "Ether Daggers",
  "/Lotus/Weapons/Tenno/Melee/DualDagger/FangPrimeDagger": "Fang Prime",
  "/Lotus/Weapons/Tenno/Melee/DualKamas/DualKamas": "Dual Kamas",
  "/Lotus/Weapons/Tenno/Melee/DualKamas/SingleKama": "Kama",
  "/Lotus/Weapons/Tenno/Melee/DualShortSword/DualEtherSword": "Dual Ether",
  "/Lotus/Weapons/Tenno/Melee/DualShortSword/DualHeatSwords": "Dual Heat Swords",
  "/Lotus/Weapons/Tenno/Melee/DualShortSword/DualShortSword": "Dual Skana",
  "/Lotus/Weapons/Tenno/Melee/Fist/Fist": "Furax",
  "/Lotus/Weapons/Tenno/Melee/Fist/FuraxWraith": "Furax Wraith",
  "/Lotus/Weapons/Tenno/Melee/Gauntlet/BrawlerKnuckles/BrawlerKnuckles": "Tekko",
  "/Lotus/Weapons/Tenno/Melee/Gauntlet/Gauntlet": "Ankyros",
  "/Lotus/Weapons/Tenno/Melee/Gauntlet/PrimeAnkyros/PrimeAnkyros": "Ankyros Prime",
  "/Lotus/Weapons/Tenno/Melee/Glaives/Boomerang/BoomerangWeapon": "Kestrel",
  "/Lotus/Weapons/Tenno/Melee/Glaives/LightGlaive/LightGlaiveWeapon": "Glaive",
  "/Lotus/Weapons/Tenno/Melee/Glaives/PrimeGlaive/PrimeGlaiveWeapon": "Glaive Prime",
  "/Lotus/Weapons/Tenno/Melee/Glaives/PrimeKestrel/PrimeKestrel": "Kestrel Prime",
  "/Lotus/Weapons/Tenno/Melee/Glaives/TeshinGlaive/TnTeshinGlaiveWep": "Orvius",
  "/Lotus/Weapons/Tenno/Melee/GreatSword/GreatSword": "Gram",
  "/Lotus/Weapons/Tenno/Melee/Gunblade/GunbladeAutomatic/TnoGunbladeAutomatic": "Sarpa",
  "/Lotus/Weapons/Tenno/Melee/Gunblade/RedeemerPrime/RedeemerPrimeWep": "Redeemer Prime",
  "/Lotus/Weapons/Tenno/Melee/Gunblade/TnoGunblade": "Redeemer",
  "/Lotus/Weapons/Tenno/Melee/Hammer/DaxDuviriHammer/DaxDuviriHammerWeapon": "Sampotes",
  "/Lotus/Weapons/Tenno/Melee/Hammer/GlassHammer/GlassHammer": "Volnus",
  "/Lotus/Weapons/Tenno/Melee/Hammer/HammerWeapon": "Fragor",
  "/Lotus/Weapons/Tenno/Melee/Hammer/IceHammer/IceHammer": "Sibear",
  "/Lotus/Weapons/Tenno/Melee/Hammer/ThrowingHammer": "Wolf Sledge",
  "/Lotus/Weapons/Tenno/Melee/HeavyScythe/DuviriScythe/DuviriHeavyScytheWeapon": "Hespar",
  "/Lotus/Weapons/Tenno/Melee/HeavyScythe/TnOrionSiriusScythe/TnOrionScytheWeapon": "Wrath",
  "/Lotus/Weapons/Tenno/Melee/HeavyScythe/TnOrionSiriusScythe/TnSiriusScytheWeapon": "Pride",
  "/Lotus/Weapons/Tenno/Melee/LongSword/EtherSword": "Ether Sword",
  "/Lotus/Weapons/Tenno/Melee/LongSword/LongSword": "Skana",
  "/Lotus/Weapons/Tenno/Melee/LongSword/SkanaPrime": "Skana Prime",
  "/Lotus/Weapons/Tenno/Melee/Maces/PaladinMace/PaladinMaceWeapon": "Magistar",
  "/Lotus/Weapons/Tenno/Melee/Nunchaku/Nunchaku/Nunchaku": "Ninkondi",
  "/Lotus/Weapons/Tenno/Melee/Nunchaku/TnoNunchaku/TnoNunchaku": "Shaku",
  "/Lotus/Weapons/Tenno/Melee/PersianMachete/DjinnMachete": "Gazal Machete",
  "/Lotus/Weapons/Tenno/Melee/Polearms/DaxDuviriPolearm/DaxDuviriPolearmWeapon": "Edun",
  "/Lotus/Weapons/Tenno/Melee/Polearms/FlowerPowerPolearm/FlowerPowerPolearmWep": "Tonbo",
  "/Lotus/Weapons/Tenno/Melee/Polearms/Naginata/ShrineMaidenNaginataWeapon": "Amanata",
  "/Lotus/Weapons/Tenno/Melee/Polearms/PolearmWeapon": "Orthos",
  "/Lotus/Weapons/Tenno/Melee/Polearms/PrimeGuandao/PrimeGuandaoWeapon": "Guandao Prime",
  "/Lotus/Weapons/Tenno/Melee/Polearms/PrimePolearmWeapon": "Orthos Prime",
  "/Lotus/Weapons/Tenno/Melee/Polearms/TnGuandaoPolearm/TnGuandaoPolearmWeapon": "Guandao",
  "/Lotus/Weapons/Tenno/Melee/Polearms/TnHalberdPolearm/TnHalberdPolearmWeapon": "Cassowar",
  "/Lotus/Weapons/Tenno/Melee/PrimeDualKamas/PrimeDualKamas": "Dual Kamas Prime",
  "/Lotus/Weapons/Tenno/Melee/PrimeFragor/PrimeFragor": "Fragor Prime",
  "/Lotus/Weapons/Tenno/Melee/PrimeKogake/KogakePrimeKnuckles": "Kogake Prime",
  "/Lotus/Weapons/Tenno/Melee/PrimeNinkondi/PrimeNikondi": "Ninkondi Prime",
  "/Lotus/Weapons/Tenno/Melee/PrimeSilvaAegis/PrimeSilvaAegis": "Silva & Aegis Prime",
  "/Lotus/Weapons/Tenno/Melee/PrimeTekko/PrimeTekko": "Tekko Prime",
  "/Lotus/Weapons/Tenno/Melee/PrimeVenKa/PrimeVenkaClaws": "Venka Prime",
  "/Lotus/Weapons/Tenno/Melee/PrimeVolnus/VolnusPrimeWeapon": "Volnus Prime",
  "/Lotus/Weapons/Tenno/Melee/Scythe/EtherScytheWeapon": "Ether Reaper",
  "/Lotus/Weapons/Tenno/Melee/Scythe/ParisScythe/ParisScythe": "Anku",
  "/Lotus/Weapons/Tenno/Melee/Scythe/PrimeVento/PrimeVentoScythe": "Venato Prime",
  "/Lotus/Weapons/Tenno/Melee/Scythe/ReaperWeapon": "Reaper Prime",
  "/Lotus/Weapons/Tenno/Melee/Scythe/StalkerScytheWeapon": "Hate",
  "/Lotus/Weapons/Tenno/Melee/Scythe/TnChoirScythe/TnChoirScythe": "Harmony",
  "/Lotus/Weapons/Tenno/Melee/Soma/SomaDualKamas": "Dual Raza",
  "/Lotus/Weapons/Tenno/Melee/Staff/GrnStaff": "Amphis",
  "/Lotus/Weapons/Tenno/Melee/Staff/MonkSpade/TnoMonkStaff": "Tipedo",
  "/Lotus/Weapons/Tenno/Melee/Staff/PrimeBo/PrimeBoWeapon": "Bo Prime",
  "/Lotus/Weapons/Tenno/Melee/Staff/SingleStaff": "Cadus",
  "/Lotus/Weapons/Tenno/Melee/Staff/Staff": "Bo",
  "/Lotus/Weapons/Tenno/Melee/Staff/TipedoPrime/TipedoPrimeWeapon": "Tipedo Prime",
  "/Lotus/Weapons/Tenno/Melee/SunDialAxe/SundialAxeWeapon": "Zenistar",
  "/Lotus/Weapons/Tenno/Melee/Swords/CrpBigSlash/CrpBigSlash": "Tenet Exec",
  "/Lotus/Weapons/Tenno/Melee/Swords/CutlassAndPoignard/CutlassPoignardSwords": "Nami Skyla",
  "/Lotus/Weapons/Tenno/Melee/Swords/CutlassAndPoignard/TennoCutlass": "Nami Solo",
  "/Lotus/Weapons/Tenno/Melee/Swords/DarkSword/DarkLongSword": "Dark Sword",
  "/Lotus/Weapons/Tenno/Melee/Swords/DarkSword/DarkSwordDaggerHybridWeapon": "Dark Split-Sword",
  "/Lotus/Weapons/Tenno/Melee/Swords/DaxDuviriKatana/DaxDuviriKatanaWeapon": "Syam",
  "/Lotus/Weapons/Tenno/Melee/Swords/DaxDuviriTwoHandedKatana/DaxDuviriTwoHandedKatanaWeapon": "Azothane",
  "/Lotus/Weapons/Tenno/Melee/Swords/DexTheSecond/DexTheSecond": "Dex Dakra",
  "/Lotus/Weapons/Tenno/Melee/Swords/GreatSword/TennoGreatSword": "Galatine",
  "/Lotus/Weapons/Tenno/Melee/Swords/HeatSword/HeatLongSword": "Heat Sword",
  "/Lotus/Weapons/Tenno/Melee/Swords/JawSword/JawLongSword": "Jaw Sword",
  "/Lotus/Weapons/Tenno/Melee/Swords/KatanaAndWakizashi/Dex2023Nikana/Dex2023Nikana": "Dex Nikana",
  "/Lotus/Weapons/Tenno/Melee/Swords/KatanaAndWakizashi/Katana": "Nikana",
  "/Lotus/Weapons/Tenno/Melee/Swords/KatanaAndWakizashi/LowKatana": "Dragon Nikana",
  "/Lotus/Weapons/Tenno/Melee/Swords/KrisDagger/KrisDagger": "Karyst",
  "/Lotus/Weapons/Tenno/Melee/Swords/NWIIIOrokinSword/NWOrokinSword": "Vitrica",
  "/Lotus/Weapons/Tenno/Melee/Swords/PRapier/DestrezaPrime": "Destreza Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PangolinSword/PangolinLongSword": "Pangolin Sword",
  "/Lotus/Weapons/Tenno/Melee/Swords/PlasmaSword/PlasmaLongSword": "Plasma Sword",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimeDualKeres/PrimeDualKeresWeapon": "Dual Keres Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimeGalatine/PrimeGalatine": "Galatine Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimeGram/PrimeGram": "Gram Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimeKaryst/PrimeKrisDagger": "Karyst Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimeKatana/PrimeNikana": "Nikana Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimeMasseter/PrimeMasseter": "Masseter Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimeNamiSkyla/PrimeNamiSkyla": "Nami Skyla Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimeOkina/PrimeOkina": "Okina Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimePangolinSword/PrimePangolinSword": "Pangolin Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimeTatsu/PrimeTatsuWeapon": "Tatsu Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/PrimeWar/PrimeWarWeapon": "War Prime",
  "/Lotus/Weapons/Tenno/Melee/Swords/QuillSword/QuillDualSwords": "Dual Keres",
  "/Lotus/Weapons/Tenno/Melee/Swords/StalkerMios/OperationsLacera": "Ceti Lacera",
  "/Lotus/Weapons/Tenno/Melee/Swords/StalkerMios/StalkerMios": "Lacera",
  "/Lotus/Weapons/Tenno/Melee/Swords/StalkerTwo/StalkerTwoGreatSword": "War",
  "/Lotus/Weapons/Tenno/Melee/Swords/StalkerTwo/StalkerTwoSmallSword": "Broken War",
  "/Lotus/Weapons/Tenno/Melee/Swords/TennoSai/TennoSais": "Okina",
  "/Lotus/Weapons/Tenno/Melee/Swords/ThreeLeaf/ThreeLeaf": "Endura",
  "/Lotus/Weapons/Tenno/Melee/Swords/TnChiselKanabo/TnChiselKanabo": "Masseter",
  "/Lotus/Weapons/Tenno/Melee/Swords/TnDagathBladeWhip/TnDagathBladeWhip": "Dorrclave",
  "/Lotus/Weapons/Tenno/Melee/Swords/TnRailjackGreatKatana/TnRailJackGreatKatanaWeapon": "Pennant",
  "/Lotus/Weapons/Tenno/Melee/Swords/TnTwoHandedKatana/TnTwoHandedKatana": "Tatsu",
  "/Lotus/Weapons/Tenno/Melee/Swords/TnoRapier/TnoRapier": "Destreza",
  "/Lotus/Weapons/Tenno/Melee/Swords/UmbraKatana/UmbraKatana": "Skiajati",
  "/Lotus/Weapons/Tenno/Melee/SwordsAndBoards/DaxDuviriMaceShieldWeapon": "Argo & Vel",
  "/Lotus/Weapons/Tenno/Melee/SwordsAndBoards/MeleeContestWinnerOne/TennoSwordShield": "Silva & Aegis",
  "/Lotus/Weapons/Tenno/Melee/SwordsAndBoards/MortiforShieldAndSword/MortiforShieldAndSword": "Tak & Lug",
  "/Lotus/Weapons/Tenno/Melee/SwordsAndBoards/PacifistShieldAndSword/PacifistShieldSword": "Cobra & Crane",
  "/Lotus/Weapons/Tenno/Melee/SwordsAndBoards/PrimeCobraAndCrane/PrimeCobraAndCraneWeapon": "Cobra & Crane Prime",
  "/Lotus/Weapons/Tenno/Melee/SwordsAndBoards/SundialSwordBoard/SundialBoardSword": "Sigma & Octantis",
  "/Lotus/Weapons/Tenno/Melee/Tonfa/Boltonfa/Boltonfa": "Boltace",
  "/Lotus/Weapons/Tenno/Melee/Tonfa/TonfaContestWinner/TennoTonfa": "Kronen",
  "/Lotus/Weapons/Tenno/Melee/Tonfa/TonfaContestWinnerPrime/TonfaContestWinnerPrimeWeapon": "Kronen Prime",
  "/Lotus/Weapons/Tenno/Melee/Warfan/PrimeGunsen/PrimeGunsenWeapon": "Gunsen Prime",
  "/Lotus/Weapons/Tenno/Melee/Warfan/PrimeQuassus/PrimeQuassusWeapon": "Quassus Prime",
  "/Lotus/Weapons/Tenno/Melee/Warfan/TnBrokenFrameWarfan/TnBrokenFrameWarfanWeapon": "Quassus",
  "/Lotus/Weapons/Tenno/Melee/Warfan/TnMoonWarfan/MoonWarfanWeapon": "Vericres",
  "/Lotus/Weapons/Tenno/Melee/Warfan/WarfanWeapon": "Gunsen",
  "/Lotus/Weapons/Tenno/Melee/Whips/SpiderWhip/SpiderWhipWeapon": "Spinnerex",
  "/Lotus/Weapons/Tenno/Pistol/AutoPistol": "Furis",
  "/Lotus/Weapons/Tenno/Pistol/BroncoPrime": "Bronco Prime",
  "/Lotus/Weapons/Tenno/Pistol/BurstPistol": "Sicarus",
  "/Lotus/Weapons/Tenno/Pistol/CrossBow": "Bolto",
  "/Lotus/Weapons/Tenno/Pistol/HandShotGun": "Bronco",
  "/Lotus/Weapons/Tenno/Pistol/HeavyPistol": "Lex",
  "/Lotus/Weapons/Tenno/Pistol/LatoPrime": "Lato Prime",
  "/Lotus/Weapons/Tenno/Pistol/LatoVandal": "Lato Vandal",
  "/Lotus/Weapons/Tenno/Pistol/Pistol": "Lato",
  "/Lotus/Weapons/Tenno/Pistol/RevolverPistol": "Vasto",
  "/Lotus/Weapons/Tenno/Pistols/1999EntHybridPistolWeapon/1999EntHybridPistolWeapon": "Riot-848",
  "/Lotus/Weapons/Tenno/Pistols/AllNew1hSG/AllNew1hSG": "Euphona Prime",
  "/Lotus/Weapons/Tenno/Pistols/AutomaticHandCrossbow/AutoCrossBow": "Ballistica",
  "/Lotus/Weapons/Tenno/Pistols/ConclaveLeverPistol/ConclaveLeverPistol": "Zylok",
  "/Lotus/Weapons/Tenno/Pistols/DexFuris/DexFuris": "Dex Furis",
  "/Lotus/Weapons/Tenno/Pistols/HarlequinGun/HarlequinPistols": "Akzani",
  "/Lotus/Weapons/Tenno/Pistols/Magnum/Magnum": "Magnus",
  "/Lotus/Weapons/Tenno/Pistols/PrimeAfuris/PrimeAFurisWeapon": "Afuris Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeAkarius/PrimeAkariusWeapon": "Akarius Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeAkbolto/PrimeAkBoltoWeapon": "Akbolto Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeAkjagara/AkJagaraPrime": "Akjagara Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeAksomati/PrimeAksomati": "Aksomati Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeAkstiletto/PrimeAkstiletto": "Akstiletto Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeAthodai/PrimeAthodaiPistolWeapon": "Athodai Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeBallistica/PrimeBallistica": "Ballistica Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeEpitaph/PrimeEpitaphSidearmWeapon": "Epitaph Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeHystrix/PrimeHystrixWeapon": "Hystrix Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeKnell/PrimeKnellWeapon": "Knell Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeKompressa/PrimeKompressa": "Kompressa Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeLex/PrimeLex": "Lex Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeMagnus/PrimeMagnusWeapon": "Magnus Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimePandero/PanderoPrimeWeapon": "Pandero Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimePyrana/PrimePyranaPistol": "Pyrana Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeSicarus/PrimeSicarusPistol": "Sicarus Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeVasto/AkPrimeVasto/AkPrimeVastoPistol": "Akvasto Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeVasto/PrimeVastoPistol": "Vasto Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeVelox/PrimeVeloxPistol": "Velox Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeZakti/PrimeZaktiPistol": "Zakti Prime",
  "/Lotus/Weapons/Tenno/Pistols/PrimeZylok/ZylokPrimePistol": "Zylok Prime",
  "/Lotus/Weapons/Tenno/Pistols/QuillDartgun/QuillDartGunWeapon": "Hystrix",
  "/Lotus/Weapons/Tenno/Pistols/SapientPistol/SapientPistol": "Akarius",
  "/Lotus/Weapons/Tenno/Pistols/SawnOffShotgun/TennoHandShotgun": "Pyrana",
  "/Lotus/Weapons/Tenno/Pistols/SomaSidearm/AkimboSomaPistols": "Aksomati",
  "/Lotus/Weapons/Tenno/Pistols/SundialGun/SundialPistol": "Azima",
  "/Lotus/Weapons/Tenno/Pistols/TennoUzi/TennoUzi": "Akstiletto",
  "/Lotus/Weapons/Tenno/Pistols/TigrisRedeemerSetPistol/TnoBladedPistols": "Akjagara",
  "/Lotus/Weapons/Tenno/Pistols/TnBardPistol/TnBardPistolGun": "Pandero",
  "/Lotus/Weapons/Tenno/Pistols/TnGuandoPistol/TnGuandoPistolGun": "Zakti",
  "/Lotus/Weapons/Tenno/Pistols/TnJetTurbine/TnJetTurbinePistolWeapon": "Athodai",
  "/Lotus/Weapons/Tenno/Pistols/TnOdaliskSmg/TnOdaliskSmgPistol": "Velox",
  "/Lotus/Weapons/Tenno/Pistols/TnPriestPistolScope/TnPriestPistolWeapon": "Knell",
  "/Lotus/Weapons/Tenno/Pistols/TnWraitheSidearm/TnWraitheSidearmWeapon": "Epitaph",
  "/Lotus/Weapons/Tenno/Pistols/TnYareliPistol/TnYareliPistolWeapon": "Kompressa",
  "/Lotus/Weapons/Tenno/Rifle/BoltoRifle": "Boltor",
  "/Lotus/Weapons/Tenno/Rifle/BratonPrime": "Braton Prime",
  "/Lotus/Weapons/Tenno/Rifle/BurstRifle": "Burston",
  "/Lotus/Weapons/Tenno/Rifle/HeavyRifle": "Gorgon",
  "/Lotus/Weapons/Tenno/Rifle/LatronPrime": "Latron Prime",
  "/Lotus/Weapons/Tenno/Rifle/Rifle": "Braton",
  "/Lotus/Weapons/Tenno/Rifle/SemiAutoRifle": "Latron",
  "/Lotus/Weapons/Tenno/Rifle/SniperRifle": "Snipetron",
  "/Lotus/Weapons/Tenno/Rifle/StartingRifle": "Mk1-Braton",
  "/Lotus/Weapons/Tenno/Rifle/TennoAR": "Soma",
  "/Lotus/Weapons/Tenno/Rifle/TennoSniperRifle": "Vectis",
  "/Lotus/Weapons/Tenno/Rifle/VIPRifle": "Braton Vandal",
  "/Lotus/Weapons/Tenno/Rifle/VandalSniperRifle": "Snipetron Vandal",
  "/Lotus/Weapons/Tenno/Shotgun/DoubleBarrelShotgun": "Sobek",
  "/Lotus/Weapons/Tenno/Shotgun/FullAutoShotgun": "Boar",
  "/Lotus/Weapons/Tenno/Shotgun/PrimeBoar": "Boar Prime",
  "/Lotus/Weapons/Tenno/Shotgun/QuadShotgun": "Hek",
  "/Lotus/Weapons/Tenno/Shotgun/Shotgun": "Strun",
  "/Lotus/Weapons/Tenno/Shotgun/ShotgunVandal": "Strun Wraith",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/GlassKunai/GlassKunaiWeapon": "Fusilai",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/Kunai": "Kunai",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/LiDagger/LiDagger": "Spira",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/PrimeLiDagger/PrimeLiDagger": "Spira Prime",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/PrimeThrowingStar/PrimeHikou": "Hikou Prime",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/StalkerKunai": "Despair",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/StickyBomb/StickyBombs": "Castanas",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/TennoStars": "Hikou",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/TnChoirframeKunai/TnChoirframeKunai": "Cantare",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/TnOraxiaFlechette/TnOraxiaFlechette": "Scyotid",
  "/Lotus/Weapons/Tenno/ThrowingWeapons/U18ThrowingKnives/U18throwingknives": "Talons",
  "/Lotus/Weapons/Tenno/Zariman/LongGuns/PumpShotgun/ZarimanPumpShotgun": "Felarx",
  "/Lotus/Weapons/Tenno/Zariman/LongGuns/SemiAutoRifle/ZarimanSemiAutoRifle": "Phenmor",
  "/Lotus/Weapons/Tenno/Zariman/Melee/Dagger/ZarimanDaggerWeapon": "Innodem",
  "/Lotus/Weapons/Tenno/Zariman/Melee/HeavyScythe/ZarimanHeavyScythe/ZarimanHeavyScytheWeapon": "Thalys",
  "/Lotus/Weapons/Tenno/Zariman/Melee/Tonfas/ZarimanTonfaWeapon": "Praedos",
  "/Lotus/Weapons/Tenno/Zariman/Pistols/HeavyPistol/ZarimanHeavyPistol": "Laetum",
  "/Lotus/Weapons/Thanotech/EntFistIncarnon/EntFistIncarnon": "Ruvox",
  "/Lotus/Weapons/Thanotech/EntSphereHammer/EntSphereHammer": "Ekhein",
  "/Lotus/Weapons/Thanotech/EntratiWristGun/EntratiWristGunWeapon": "Onos",
  "/Lotus/Weapons/Thanotech/ThanoPistol/ThanotechPistol": "Sepulcrum",
  "/Lotus/Weapons/Thanotech/ThanoRifle/ThanotechRifle": "Trumna",
  "/Lotus/Weapons/VoidTrader/PrismaGrakata": "Prisma Grakata",
  "/Lotus/Weapons/VoidTrader/PrismaSkana": "Prisma Skana",
  "/Lotus/Weapons/VoidTrader/VTDetron": "Mara Detron"
}
