// AUTO-GENERATED — DE quest key ItemType (uniqueName) → quest name, for the
// progression guide (#58). The inventory QuestKeys array carries these with a
// Completed flag. Regenerate with scripts/gen-quests.mjs. 43 entries.
export const QUEST_NAMES: Record<string, string> = {
  "/Lotus/Types/Keys/1999PrologueQuest/1999PrologueQuestKeyChain": "The Lotus Eaters",
  "/Lotus/Types/Keys/1999Quest/1999QuestGoodEndKeyChain": "The Hex Finale",
  "/Lotus/Types/Keys/1999Quest/1999QuestKeyChain": "The Hex",
  "/Lotus/Types/Keys/ApostasyQuest/ApostasyKeyChain": "Apostasy Prologue",
  "/Lotus/Types/Keys/ArchwingQuest/ArchwingQuestKeyChain": "The Archwing",
  "/Lotus/Types/Keys/BardQuest/BardQuestKeyChain": "Octavia's Anthem",
  "/Lotus/Types/Keys/ChimeraQuest/ChimeraKeyChain": "Chimera Prologue",
  "/Lotus/Types/Keys/DragonQuest/DragonQuestKeyChain": "The New Strange",
  "/Lotus/Types/Keys/DuviriQuest/DuviriQuestKeyChain": "The Duviri Paradox",
  "/Lotus/Types/Keys/EntratiLab/EntratiQuestKeyChain": "Whispers In The Walls",
  "/Lotus/Types/Keys/FairyQuest/FairyQuestKeyChain": "The Silver Grove",
  "/Lotus/Types/Keys/GetClemQuest/GetClemQuestKeyChain": "A Man Of Few Words",
  "/Lotus/Types/Keys/GlassQuest/GlassQuestKeyChain": "Saya's Vigil",
  "/Lotus/Types/Keys/IndexQuest/IndexQuestKeyChain": "The Glast Gambit",
  "/Lotus/Types/Keys/InfestedAladVQuest/InfestedAladVQuestKeyChain": "Patient Zero",
  "/Lotus/Types/Keys/InfestedIntroQuest/InfestedIntroQuestKeyChain": "Once Awake",
  "/Lotus/Types/Keys/InfestedMicroplanetQuest/InfestedMicroplanetQuestKeyChain": "Heart Of Deimos",
  "/Lotus/Types/Keys/JadeShadows/JadeShadowQuestKeyChain": "Jade Shadows",
  "/Lotus/Types/Keys/JadeShadowsPart2Constellations/JadeShadowsPart2QuestKeyChain": "Jade Shadows: Constellations",
  "/Lotus/Types/Keys/KahlQuest/KahlQuestKeyChain": "Veilbreaker",
  "/Lotus/Types/Keys/KubrowQuest/KubrowQuestKeyChain": "Howl Of The Kubrow",
  "/Lotus/Types/Keys/LimboQuest/LimboQuestKeyChain": "The Limbo Theorem",
  "/Lotus/Types/Keys/MirageQuest/MirageQuestKeyChain": "Hidden Messages",
  "/Lotus/Types/Keys/ModQuest/ModQuestKeyChain": "The Teacher",
  "/Lotus/Types/Keys/MummyQuest/MummyQuestKeyChain": "Sands Of Inaros",
  "/Lotus/Types/Keys/NewPlayerQuest/NewPlayerQuestKeyChain": "Awakening",
  "/Lotus/Types/Keys/NewWarIntroQuest/NewWarIntroKeyChain": "Erra",
  "/Lotus/Types/Keys/NewWarQuest/NewWarQuestKeyChain": "The New War",
  "/Lotus/Types/Keys/OrokinMoonQuest/OrokinMoonQuestKeyChain": "The Second Dream",
  "/Lotus/Types/Keys/PriestFrameQuest/PriestQuestKeyChain": "Chains Of Harrow",
  "/Lotus/Types/Keys/ProteaQuest/ProteaQuestKeyChain": "The Deadlock Protocol",
  "/Lotus/Types/Keys/RailJackBuildQuest/RailjackBuildQuestKeyChain": "Rising Tide",
  "/Lotus/Types/Keys/RevenantQuest/RevenantQuestKeyChain": "Mask Of The Revenant",
  "/Lotus/Types/Keys/SacrificeQuest/SacrificeQuestKeyChain": "The Sacrifice",
  "/Lotus/Types/Keys/SentientQuest/SentientQuestKeyChain": "Natah",
  "/Lotus/Types/Keys/SolarisQuest/SolarisQuestKeyChain": "Vox Solaris",
  "/Lotus/Types/Keys/SpyQuestKeyChain/SpyQuestKeyChain": "Stolen Dreams",
  "/Lotus/Types/Keys/TauPrequel/TauPrequelQuestKeyChain": "The Old Peace",
  "/Lotus/Types/Keys/VorsPrize/VorsPrizeQuestKeyChain": "Vor's Prize",
  "/Lotus/Types/Keys/WarWithinQuest/WarWithinQuestKeyChain": "The War Within",
  "/Lotus/Types/Keys/WraithQuest/WraithQuestKeyChain": "Call Of The Tempestarii",
  "/Lotus/Types/Keys/YareliQuest/YareliQuestKeyChain": "The Waverider",
  "/Lotus/Types/Keys/ZarimanQuest/ZarimanQuestKeyChain": "Angels Of The Zariman"
}
