// AUTO-GENERATED — DE inventory ItemType (uniqueName) → crafting resource name,
// for the Foundry owned-vs-needed component counts (#66). Resources live in the
// DE inventory MiscItems array keyed by uniqueName. Regenerate: scripts/gen-resources.mjs.
// 57 entries.
export const RESOURCE_NAMES: Record<string, string> = {
  "/Lotus/Types/Items/MiscItems/Alertium": "Nitain Extract",
  "/Lotus/Types/Items/MiscItems/AlloyPlate": "Alloy Plate",
  "/Lotus/Types/Items/MiscItems/ArgonCrystal": "Argon Crystal",
  "/Lotus/Types/Items/MiscItems/Beacon": "Proof Fragment",
  "/Lotus/Types/Items/MiscItems/Circuits": "Circuits",
  "/Lotus/Types/Items/MiscItems/ConcentratedGas": "Hexenon",
  "/Lotus/Types/Items/MiscItems/ControlModule": "Control Module",
  "/Lotus/Types/Items/MiscItems/Cryotic": "Cryotic",
  "/Lotus/Types/Items/MiscItems/Eidolonium": "Breath Of The Eidolon",
  "/Lotus/Types/Items/MiscItems/Elitium": "Vitus Essence",
  "/Lotus/Types/Items/MiscItems/Eventium": "Synthula",
  "/Lotus/Types/Items/MiscItems/Ferrite": "Ferrite",
  "/Lotus/Types/Items/MiscItems/FocusLensGreater": "Greater Focus Lens",
  "/Lotus/Types/Items/MiscItems/FocusLensOstron": "Eidolon Lens",
  "/Lotus/Types/Items/MiscItems/Forma": "Forma",
  "/Lotus/Types/Items/MiscItems/Gallium": "Gallium",
  "/Lotus/Types/Items/MiscItems/GrnFlameSpearPart": "Javlok Capacitor",
  "/Lotus/Types/Items/MiscItems/InfestedAladCoordinate": "Mutalist Alad V Nav Coordinate",
  "/Lotus/Types/Items/MiscItems/JuggernautPartA": "Pulsating Tubercles",
  "/Lotus/Types/Items/MiscItems/JuggernautPartB": "Infected Palpators",
  "/Lotus/Types/Items/MiscItems/JuggernautPartC": "Chitinous Husk",
  "/Lotus/Types/Items/MiscItems/JuggernautPartD": "Severed Bile Sac",
  "/Lotus/Types/Items/MiscItems/Kuva": "Kuva",
  "/Lotus/Types/Items/MiscItems/MemoryCryptoFragment": "Somatic Fibers",
  "/Lotus/Types/Items/MiscItems/MirageCode": "Orokin Cipher",
  "/Lotus/Types/Items/MiscItems/Morphic": "Morphics",
  "/Lotus/Types/Items/MiscItems/Nanospores": "Nano Spores",
  "/Lotus/Types/Items/MiscItems/NarmerBountyResource": "Narmer Isoplast",
  "/Lotus/Types/Items/MiscItems/NavCode": "Nav Coordinate",
  "/Lotus/Types/Items/MiscItems/NeuralSensor": "Neural Sensors",
  "/Lotus/Types/Items/MiscItems/Neurode": "Neurodes",
  "/Lotus/Types/Items/MiscItems/OmegaIsotope": "Omega Isotope",
  "/Lotus/Types/Items/MiscItems/OrokinCell": "Orokin Cell",
  "/Lotus/Types/Items/MiscItems/OxiumAlloy": "Oxium",
  "/Lotus/Types/Items/MiscItems/Plastids": "Plastids",
  "/Lotus/Types/Items/MiscItems/PolymerBundle": "Polymer Bundle",
  "/Lotus/Types/Items/MiscItems/PrimeBucks": "Orokin Ducats",
  "/Lotus/Types/Items/MiscItems/RazorbackCipherPart": "Cryptographic Alu",
  "/Lotus/Types/Items/MiscItems/Rubedo": "Rubedo",
  "/Lotus/Types/Items/MiscItems/Salvage": "Salvage",
  "/Lotus/Types/Items/MiscItems/SentientFragmentLootItem": "Anomaly Shard",
  "/Lotus/Types/Items/MiscItems/ShrineFragment": "Fate Pearl",
  "/Lotus/Types/Items/MiscItems/SpecterParticleResidue": "Spectral Debris",
  "/Lotus/Types/Items/MiscItems/SyringeComponent": "Antiserum Injector Fragment",
  "/Lotus/Types/Items/MiscItems/Tellurium": "Tellurium",
  "/Lotus/Types/Items/MiscItems/VoidTearDrop": "Void Traces",
  "/Lotus/Types/Items/Plants/MiscItems/CommonDayPlantItem": "Sunlight Threshcone",
  "/Lotus/Types/Items/Plants/MiscItems/CommonNightPlantItem": "Moonlight Threshcone",
  "/Lotus/Types/Items/Plants/MiscItems/GftPlantRuksClawMaturePlantItem": "Ruk's Claw",
  "/Lotus/Types/Items/Plants/MiscItems/MossGroundCoverAPlantItem": "Vestan Moss",
  "/Lotus/Types/Items/Plants/MiscItems/RareDayPlantItem": "Sunlight Jadeleaf",
  "/Lotus/Types/Items/Plants/MiscItems/RareNightPlantItem": "Moonlight Jadeleaf",
  "/Lotus/Types/Items/Plants/MiscItems/UnCommonDayPlantItem": "Sunlight Dragonlily",
  "/Lotus/Types/Items/Plants/MiscItems/UnCommonNightPlantItem": "Moonlight Dragonlily",
  "/Lotus/Types/Items/Plants/MiscItems/WildGingerBPlantItem": "Frostleaf",
  "/Lotus/Types/Items/Plants/MiscItems/ZenCobraLotusPlantItem": "Dusklight Sarracenia",
  "/Lotus/Types/Items/Plants/MiscItems/ZenPitcherPlantItem": "Lunar Pitcher"
}
