// AUTO-GENERATED — DE inventory ItemType (uniqueName) → crafting resource name,
// for the Foundry owned-vs-needed component counts (#66/#95). Collected from every
// WFCD recipe component under /Types/Items/ (MiscItems, Research, Deimos/fish/tags),
// excluding tradable prime parts. Regenerate: scripts/gen-resources.mjs.
// 233 entries. Keys are normalized: /StoreItems/Types/ -> /Types/.
export const RESOURCE_NAMES: Record<string, string> = {
  "/Lotus/Types/Items/Deimos/AnimalTagInfestedKdriveCommon": "Purple Velocipod Tag",
  "/Lotus/Types/Items/Deimos/AnimalTagInfestedPredatorCommon": "Vizier Predasite Tag",
  "/Lotus/Types/Items/Deimos/SeriglassShard": "Seriglass Shard",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosGenericInfestedFishPartItem": "Ferment Bladder",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosGenericOrokinFishPartItem": "Tubercular Gill System",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosGenericSharedFishPartItem": "Benign Infested Tumor",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosInfestedFishAPartItem": "Pustulent Cognitive Nodule",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosInfestedFishBPartItem": "Dendrite Blastoma",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosInfestedFishCPartItem": "Saturated Muscle Mass",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosInfestedFishDPartItem": "Waxen Sebum Deposit",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosInfestedFishEPartItem": "Sporulate Sac",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosInfestedFishFPartItem": "Ocular Stem-Root",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosInfestedFishGPartItem": "Parasitic Tethermaw",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosOrokinFishAPartItem": "Biotic Filter",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosOrokinFishBPartItem": "Spinal Core Section",
  "/Lotus/Types/Items/Fish/Deimos/FishParts/DeimosOrokinFishCPartItem": "Cranial Foremount",
  "/Lotus/Types/Items/Fish/Deimos/HybridRareAFishItemLarge": "Aquapulmo",
  "/Lotus/Types/Items/Fish/Deimos/HybridUncommonAFishItemLarge": "Ostimyr",
  "/Lotus/Types/Items/Fish/Deimos/HybridUncommonBFishItemLarge": "Vitreospina",
  "/Lotus/Types/Items/Fish/Deimos/InfestedCommonAFishItemLarge": "Cryptosuctus",
  "/Lotus/Types/Items/Fish/Deimos/InfestedCommonBFishItemLarge": "Barbisteo",
  "/Lotus/Types/Items/Fish/Deimos/InfestedCommonCFishItemLarge": "Kymaeros",
  "/Lotus/Types/Items/Fish/Deimos/InfestedCommonDFishItemLarge": "Amniophysi",
  "/Lotus/Types/Items/Fish/Deimos/InfestedCommonEFishItemLarge": "Lobotriscid",
  "/Lotus/Types/Items/Fish/Deimos/InfestedRareAFishItemLarge": "Flagellocanth",
  "/Lotus/Types/Items/Fish/Deimos/InfestedUncommonAFishItemLarge": "Glutinox",
  "/Lotus/Types/Items/Fish/Deimos/OrokinLegendaryAFishItemLarge": "Myxostomata",
  "/Lotus/Types/Items/Fish/Deimos/OrokinRareAFishItemLarge": "Duroid",
  "/Lotus/Types/Items/Fish/Deimos/OrokinUncommonAFishItemLarge": "Chondricord",
  "/Lotus/Types/Items/Fish/Eidolon/BothCommonFishAItemLarge": "Charc Eel",
  "/Lotus/Types/Items/Fish/Eidolon/BothCommonFishBItemLarge": "Goopolla",
  "/Lotus/Types/Items/Fish/Eidolon/BothRareFishAItemLarge": "Murkray",
  "/Lotus/Types/Items/Fish/Eidolon/BothUncommonFishAItemLarge": "Sharrac",
  "/Lotus/Types/Items/Fish/Eidolon/BothUncommonFishBItemLarge": "Karkina",
  "/Lotus/Types/Items/Fish/Eidolon/DayCommonFishAItemLarge": "Mawfish",
  "/Lotus/Types/Items/Fish/Eidolon/DayCommonFishBItemLarge": "Khut-Khut",
  "/Lotus/Types/Items/Fish/Eidolon/DayCommonFishCItemLarge": "Yogwun",
  "/Lotus/Types/Items/Fish/Eidolon/DayUncommonFishAItemLarge": "Tralok",
  "/Lotus/Types/Items/Fish/Eidolon/DayUncommonFishBItemLarge": "Mortus Lungfish",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/BothCommonFishAPartItem": "Charc Electroplax",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/BothCommonFishBPartItem": "Goopolla Spleen",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/BothRareFishAPartItem": "Murkray Liver",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/BothUncommonFishAPartItem": "Sharrac Teeth",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/BothUncommonFishBPartItem": "Karkina Antenna",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/DayCommonFishAPartItem": "Mawfish Bones",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/DayCommonFishBPartItem": "Khut-Khut Venom Sac",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/DayCommonFishCPartItem": "Yogwun Stomach",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/DayUncommonFishAPartItem": "Tralok Eyes",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/DayUncommonFishBPartItem": "Mortus Horn",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/EidolonFishMeatItem": "Fish Meat",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/EidolonFishOilItem": "Fish Oil",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/EidolonFishScalesItem": "Fish Scales",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/NightLegendaryFishAPartItem": "Seram Beetle Shell",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/NightRareFishAPartItem": "Norg Brain",
  "/Lotus/Types/Items/Fish/Eidolon/FishParts/NightRareFishBPartItem": "Cuthol Tendrils",
  "/Lotus/Types/Items/Fish/Eidolon/GrineerBootItem": "Boot",
  "/Lotus/Types/Items/Fish/Eidolon/NightLegendaryFishAItemLarge": "Glappid",
  "/Lotus/Types/Items/Fish/Eidolon/NightRareFishAItemLarge": "Norg",
  "/Lotus/Types/Items/Fish/Eidolon/NightRareFishBItemLarge": "Cuthol",
  "/Lotus/Types/Items/Fish/Solaris/CorpusBootItem": "Crewman's Boot",
  "/Lotus/Types/Items/Fish/Solaris/CorpusBothUncommonFishALargeItem": "Mirewinder",
  "/Lotus/Types/Items/Fish/Solaris/CorpusCoolCommonFishALargeItem": "Sapcaddy",
  "/Lotus/Types/Items/Fish/Solaris/CorpusCoolUncommonFishALargeItem": "Eye-Eye",
  "/Lotus/Types/Items/Fish/Solaris/CorpusWarmCommonFishALargeItem": "Echowinder",
  "/Lotus/Types/Items/Fish/Solaris/CorpusWarmCommonFishBLargeItem": "Brickie",
  "/Lotus/Types/Items/Fish/Solaris/CorpusWarmUncommonFishALargeItem": "Kriller",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/CorpusFishAnoscopicSensorItem": "Echowinder Anoscopic Sensor",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/CorpusFishExaBrainItem": "Scrubber Exa Brain",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/CorpusFishMuonBatteryItem": "Brickie Muon Battery",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/CorpusFishParralelBiodeItem": "Mirewinder Parallel Biode",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/CorpusFishRotobladeItem": "Eye-Eye Rotoblade",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/CorpusFishThermalLaserItem": "Kriller Thermal Laser",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/CorpusFishVenedoCaseItem": "Sapcaddy Venedo Case",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/GenericFishScrapItem": "Scrap",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/OrokinFishEcosynthAnalyzerItem": "Synathid Ecosynth Analyzer",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/OrokinFishEntroplasmaItem": "Tromyzon Entroplasma",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/OrokinFishSaganModuleItem": "Charamote Sagan Module",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/SolarisFishDissipatorCoilItem": "Tink Dissipator Coil",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/SolarisFishLatheCoogulantItem": "Longwinder Lathe Coagulant",
  "/Lotus/Types/Items/Fish/Solaris/FishParts/SolarisFishNeuralRelayItem": "Recaster Neural Relay",
  "/Lotus/Types/Items/Fish/Solaris/OrokinBothLegendaryFishALargeItem": "Synathid",
  "/Lotus/Types/Items/Fish/Solaris/OrokinBothRareFishALargeItem": "Charamote",
  "/Lotus/Types/Items/Fish/Solaris/OrokinCoolRareFishALargeItem": "Tromyzon",
  "/Lotus/Types/Items/Fish/Solaris/SolarisBothCommonFishALargeItem": "Scrubber",
  "/Lotus/Types/Items/Fish/Solaris/SolarisCoolCommonFishALargeItem": "Tink",
  "/Lotus/Types/Items/Fish/Solaris/SolarisCoolUncommonFishALargeItem": "Recaster",
  "/Lotus/Types/Items/Fish/Solaris/SolarisWarmRareFishALargeItem": "Longwinder",
  "/Lotus/Types/Items/FusionTreasures/OroFusexOrnamentA": "Ayatan Cyan Star",
  "/Lotus/Types/Items/Gems/Deimos/DeimosCommonGemACutItem": "Faceted Tiametrite",
  "/Lotus/Types/Items/Gems/Deimos/DeimosCommonGemAItem": "Tiametrite",
  "/Lotus/Types/Items/Gems/Deimos/DeimosCommonGemBCutItem": "Purged Dagonic",
  "/Lotus/Types/Items/Gems/Deimos/DeimosCommonGemBItem": "Dagonic",
  "/Lotus/Types/Items/Gems/Deimos/DeimosCommonOreAAlloyItem": "Adramal Alloy",
  "/Lotus/Types/Items/Gems/Deimos/DeimosCommonOreAItem": "Adramalium",
  "/Lotus/Types/Items/Gems/Deimos/DeimosCommonOreBAlloyItem": "Tempered Bapholite",
  "/Lotus/Types/Items/Gems/Deimos/DeimosCommonOreBItem": "Bapholite",
  "/Lotus/Types/Items/Gems/Deimos/DeimosEidolonGemACutItem": "Trapezium Xenorhast",
  "/Lotus/Types/Items/Gems/Deimos/DeimosEidolonGemAItem": "Xenorhast",
  "/Lotus/Types/Items/Gems/Deimos/DeimosEidolonGemBCutItem": "Cabochon Embolos",
  "/Lotus/Types/Items/Gems/Deimos/DeimosEidolonGemBItem": "Embolos",
  "/Lotus/Types/Items/Gems/Deimos/DeimosRareGemACutItem": "Stellated Necrathene",
  "/Lotus/Types/Items/Gems/Deimos/DeimosRareGemAItem": "Necrathene",
  "/Lotus/Types/Items/Gems/Deimos/DeimosRareOreAAlloyItem": "Thaumic Distillate",
  "/Lotus/Types/Items/Gems/Deimos/DeimosRareOreAItem": "Thaumica",
  "/Lotus/Types/Items/Gems/Deimos/DeimosUncommonGemACutItem": "Purified Heciphron",
  "/Lotus/Types/Items/Gems/Deimos/DeimosUncommonGemAItem": "Heciphron",
  "/Lotus/Types/Items/Gems/Deimos/DeimosUncommonOreAAlloyItem": "Devolved Namalon",
  "/Lotus/Types/Items/Gems/Deimos/DeimosUncommonOreAItem": "Namalon",
  "/Lotus/Types/Items/Gems/Eidolon/CommonGemACutAItem": "Tear Azurite",
  "/Lotus/Types/Items/Gems/Eidolon/CommonGemAItem": "Azurite",
  "/Lotus/Types/Items/Gems/Eidolon/CommonGemBCutAItem": "Esher Devar",
  "/Lotus/Types/Items/Gems/Eidolon/CommonGemBItem": "Devar",
  "/Lotus/Types/Items/Gems/Eidolon/CommonOreAAlloyAItem": "Pyrotic Alloy",
  "/Lotus/Types/Items/Gems/Eidolon/CommonOreAItem": "Pyrol",
  "/Lotus/Types/Items/Gems/Eidolon/CommonOreBAlloyBItem": "Coprite Alloy",
  "/Lotus/Types/Items/Gems/Eidolon/CommonOreBItem": "Coprun",
  "/Lotus/Types/Items/Gems/Eidolon/EidolonGemACutAItem": "Radian Sentirum",
  "/Lotus/Types/Items/Gems/Eidolon/EidolonGemAItem": "Sentirum",
  "/Lotus/Types/Items/Gems/Eidolon/EidolonGemBCutAItem": "Heart Nyth",
  "/Lotus/Types/Items/Gems/Eidolon/EidolonGemBItem": "Nyth",
  "/Lotus/Types/Items/Gems/Eidolon/RareGemACutAItem": "Star Crimzian",
  "/Lotus/Types/Items/Gems/Eidolon/RareGemAItem": "Crimzian",
  "/Lotus/Types/Items/Gems/Eidolon/RareOreAAlloyAItem": "Auroxium Alloy",
  "/Lotus/Types/Items/Gems/Eidolon/RareOreAItem": "Auron",
  "/Lotus/Types/Items/Gems/Eidolon/UncommonGemACutAItem": "Marquise Veridos",
  "/Lotus/Types/Items/Gems/Eidolon/UncommonGemAItem": "Veridos",
  "/Lotus/Types/Items/Gems/Eidolon/UncommonOreAAlloyAItem": "Fersteel Alloy",
  "/Lotus/Types/Items/Gems/Eidolon/UncommonOreAItem": "Ferros",
  "/Lotus/Types/Items/Gems/Solaris/SolarisCommonGemACutItem": "Smooth Phasmin",
  "/Lotus/Types/Items/Gems/Solaris/SolarisCommonGemAItem": "Phasmin",
  "/Lotus/Types/Items/Gems/Solaris/SolarisCommonGemBCutItem": "Heart Noctrul",
  "/Lotus/Types/Items/Gems/Solaris/SolarisCommonGemBItem": "Noctrul",
  "/Lotus/Types/Items/Gems/Solaris/SolarisCommonOreAAlloyItem": "Travocyte Alloy",
  "/Lotus/Types/Items/Gems/Solaris/SolarisCommonOreAItem": "Travoride",
  "/Lotus/Types/Items/Gems/Solaris/SolarisCommonOreBAlloyItem": "Axidrol Alloy",
  "/Lotus/Types/Items/Gems/Solaris/SolarisCommonOreBItem": "Axidite",
  "/Lotus/Types/Items/Gems/Solaris/SolarisEidolonGemACutItem": "Radiant Zodian",
  "/Lotus/Types/Items/Gems/Solaris/SolarisEidolonGemAItem": "Zodian",
  "/Lotus/Types/Items/Gems/Solaris/SolarisEidolonGemBCutItem": "Marquise Thyst",
  "/Lotus/Types/Items/Gems/Solaris/SolarisEidolonGemBItem": "Thyst",
  "/Lotus/Types/Items/Gems/Solaris/SolarisRareGemACutItem": "Star Amarast",
  "/Lotus/Types/Items/Gems/Solaris/SolarisRareGemAItem": "Amarast",
  "/Lotus/Types/Items/Gems/Solaris/SolarisRareOreAAlloyItem": "Hespazym Alloy",
  "/Lotus/Types/Items/Gems/Solaris/SolarisRareOreAItem": "Hesperon",
  "/Lotus/Types/Items/Gems/Solaris/SolarisUncommonGemACutItem": "Goblite Tears",
  "/Lotus/Types/Items/Gems/Solaris/SolarisUncommonGemAItem": "Goblite",
  "/Lotus/Types/Items/Gems/Solaris/SolarisUncommonOreAAlloyItem": "Venerdo Alloy",
  "/Lotus/Types/Items/Gems/Solaris/SolarisUncommonOreItem": "Venerol",
  "/Lotus/Types/Items/MiscItems/Alertium": "Nitain Extract",
  "/Lotus/Types/Items/MiscItems/AlloyPlate": "Alloy Plate",
  "/Lotus/Types/Items/MiscItems/ArgonCrystal": "Argon Crystal",
  "/Lotus/Types/Items/MiscItems/Beacon": "Proof Fragment",
  "/Lotus/Types/Items/MiscItems/Circuits": "Circuits",
  "/Lotus/Types/Items/MiscItems/ConcentratedGas": "Hexenon",
  "/Lotus/Types/Items/MiscItems/ControlModule": "Control Module",
  "/Lotus/Types/Items/MiscItems/Cryotic": "Cryotic",
  "/Lotus/Types/Items/MiscItems/Eidolonium": "Breath Of The Eidolon",
  "/Lotus/Types/Items/MiscItems/Elitium": "Vitus Essence",
  "/Lotus/Types/Items/MiscItems/Eventium": "Synthula",
  "/Lotus/Types/Items/MiscItems/Ferrite": "Ferrite",
  "/Lotus/Types/Items/MiscItems/FocusLensGreater": "Greater Focus Lens",
  "/Lotus/Types/Items/MiscItems/FocusLensOstron": "Eidolon Lens",
  "/Lotus/Types/Items/MiscItems/Forma": "Forma",
  "/Lotus/Types/Items/MiscItems/Gallium": "Gallium",
  "/Lotus/Types/Items/MiscItems/GrnFlameSpearPart": "Javlok Capacitor",
  "/Lotus/Types/Items/MiscItems/InfestedAladCoordinate": "Mutalist Alad V Nav Coordinate",
  "/Lotus/Types/Items/MiscItems/JuggernautPartA": "Pulsating Tubercles",
  "/Lotus/Types/Items/MiscItems/JuggernautPartB": "Infected Palpators",
  "/Lotus/Types/Items/MiscItems/JuggernautPartC": "Chitinous Husk",
  "/Lotus/Types/Items/MiscItems/JuggernautPartD": "Severed Bile Sac",
  "/Lotus/Types/Items/MiscItems/Kuva": "Kuva",
  "/Lotus/Types/Items/MiscItems/MemoryCryptoFragment": "Somatic Fibers",
  "/Lotus/Types/Items/MiscItems/MirageCode": "Orokin Cipher",
  "/Lotus/Types/Items/MiscItems/Morphic": "Morphics",
  "/Lotus/Types/Items/MiscItems/Nanospores": "Nano Spores",
  "/Lotus/Types/Items/MiscItems/NarmerBountyResource": "Narmer Isoplast",
  "/Lotus/Types/Items/MiscItems/NavCode": "Nav Coordinate",
  "/Lotus/Types/Items/MiscItems/NeuralSensor": "Neural Sensors",
  "/Lotus/Types/Items/MiscItems/Neurode": "Neurodes",
  "/Lotus/Types/Items/MiscItems/OmegaIsotope": "Omega Isotope",
  "/Lotus/Types/Items/MiscItems/OrokinCell": "Orokin Cell",
  "/Lotus/Types/Items/MiscItems/OxiumAlloy": "Oxium",
  "/Lotus/Types/Items/MiscItems/Plastids": "Plastids",
  "/Lotus/Types/Items/MiscItems/PolymerBundle": "Polymer Bundle",
  "/Lotus/Types/Items/MiscItems/PrimeBucks": "Orokin Ducats",
  "/Lotus/Types/Items/MiscItems/RazorbackCipherPart": "Cryptographic Alu",
  "/Lotus/Types/Items/MiscItems/Rubedo": "Rubedo",
  "/Lotus/Types/Items/MiscItems/Salvage": "Salvage",
  "/Lotus/Types/Items/MiscItems/SentientFragmentLootItem": "Anomaly Shard",
  "/Lotus/Types/Items/MiscItems/ShrineFragment": "Fate Pearl",
  "/Lotus/Types/Items/MiscItems/SpecterParticleResidue": "Spectral Debris",
  "/Lotus/Types/Items/MiscItems/SyringeComponent": "Antiserum Injector Fragment",
  "/Lotus/Types/Items/MiscItems/Tellurium": "Tellurium",
  "/Lotus/Types/Items/MiscItems/VoidTearDrop": "Void Traces",
  "/Lotus/Types/Items/MushroomJournal/BlastMushroomJournalItem": "Spring Popper",
  "/Lotus/Types/Items/MushroomJournal/ColdMushroomJournalItem": "Winter Spear",
  "/Lotus/Types/Items/MushroomJournal/CorrosiveMushroomJournalItem": "Borica",
  "/Lotus/Types/Items/MushroomJournal/ElectricMushroomJournalItem": "Thunder-Button",
  "/Lotus/Types/Items/MushroomJournal/GasMushroomJournalItem": "Reeking Puffball",
  "/Lotus/Types/Items/MushroomJournal/HeatMushroomJournalItem": "Blister Stalk",
  "/Lotus/Types/Items/MushroomJournal/ImpactMushroomJournalItem": "Ironwood",
  "/Lotus/Types/Items/MushroomJournal/MagneticMushroomJournalItem": "Ferrofungus",
  "/Lotus/Types/Items/MushroomJournal/PlainMushroomJournalItem": "Dull Button",
  "/Lotus/Types/Items/MushroomJournal/PunctureMushroomJournalItem": "Thorn Tooth",
  "/Lotus/Types/Items/MushroomJournal/RadiationMushroomJournalItem": "Gamma Berry",
  "/Lotus/Types/Items/MushroomJournal/SlashMushroomJournalItem": "Devil's Cap",
  "/Lotus/Types/Items/MushroomJournal/TauMushroomJournalItem": "Vomval Trumpet",
  "/Lotus/Types/Items/MushroomJournal/ToxinMushroomJournalItem": "Muck Bonnet",
  "/Lotus/Types/Items/MushroomJournal/ViralMushroomJournalItem": "Violet's Bane",
  "/Lotus/Types/Items/MushroomJournal/VoidMushroomJournalItem": "Nonono",
  "/Lotus/Types/Items/Plants/MiscItems/CommonDayPlantItem": "Sunlight Threshcone",
  "/Lotus/Types/Items/Plants/MiscItems/CommonNightPlantItem": "Moonlight Threshcone",
  "/Lotus/Types/Items/Plants/MiscItems/GftPlantRuksClawMaturePlantItem": "Ruk's Claw",
  "/Lotus/Types/Items/Plants/MiscItems/MossGroundCoverAPlantItem": "Vestan Moss",
  "/Lotus/Types/Items/Plants/MiscItems/RareDayPlantItem": "Sunlight Jadeleaf",
  "/Lotus/Types/Items/Plants/MiscItems/RareNightPlantItem": "Moonlight Jadeleaf",
  "/Lotus/Types/Items/Plants/MiscItems/UnCommonDayPlantItem": "Sunlight Dragonlily",
  "/Lotus/Types/Items/Plants/MiscItems/UnCommonNightPlantItem": "Moonlight Dragonlily",
  "/Lotus/Types/Items/Plants/MiscItems/WildGingerBPlantItem": "Frostleaf",
  "/Lotus/Types/Items/Plants/MiscItems/ZenCobraLotusPlantItem": "Dusklight Sarracenia",
  "/Lotus/Types/Items/Plants/MiscItems/ZenPitcherPlantItem": "Lunar Pitcher",
  "/Lotus/Types/Items/RailjackMiscItems/CarbidesRailjackItem": "Carbides",
  "/Lotus/Types/Items/RailjackMiscItems/IsosRailjackItem": "Isos",
  "/Lotus/Types/Items/RailjackMiscItems/KommsRailjackItem": "Komms",
  "/Lotus/Types/Items/RailjackMiscItems/NullstonesRailjackItem": "Nullstones",
  "/Lotus/Types/Items/RailjackMiscItems/TitaniumRailjackItem": "Titanium",
  "/Lotus/Types/Items/RelayRebuild/PhaseThreeEarthEssence": "Trembera Essence",
  "/Lotus/Types/Items/Research/BioComponent": "Mutagen Mass",
  "/Lotus/Types/Items/Research/BioFragment": "Mutagen Sample",
  "/Lotus/Types/Items/Research/ChemComponent": "Detonite Injector",
  "/Lotus/Types/Items/Research/ChemFragment": "Detonite Ampule",
  "/Lotus/Types/Items/Research/EnergyComponent": "Fieldron",
  "/Lotus/Types/Items/Research/EnergyFragment": "Fieldron Sample"
}

// resourceName resolves a DE inventory ItemType to its resource name, tolerating
// the StoreItems-prefixed variant DE uses for resources that are also sold
// (Kuva, Forma). Returns undefined when the ItemType isn't a known resource.
export function resourceName(itemType: string): string | undefined {
  if (!itemType) return undefined
  return (
    RESOURCE_NAMES[itemType] ??
    RESOURCE_NAMES[itemType.replace('/StoreItems/Types/', '/Types/')]
  )
}
